/**
 * ESLint for FF Beacon (plan IDP-401, owner decision 2026-09-24).
 *
 * Run with `npm run lint`. It is part of the gate beside typecheck, tests and
 * build, and it must finish with zero errors AND zero warnings: every
 * exception in the code carries an eslint-disable comment that says why.
 *
 * Layers, in order:
 *   1. Next's own presets (core web vitals, TypeScript), through FlatCompat
 *      because eslint-config-next 15 ships the older config format.
 *   2. jsx-a11y's full recommended set. Next enables only six of its rules;
 *      accessibility is this product's core differentiator, so all of them.
 *   3. FF Beacon's own rules (scripts/eslint/ffbeacon-plugin.mjs): ASCII
 *      punctuation, Sleeper calls only through lib/sleeper.ts, and dates always
 *      formatted in a named zone.
 *
 * `next build` does not run this (next.config.ts sets
 * eslint.ignoreDuringBuilds): lint is a gate for changes, not a way for a
 * deploy to fail, and Next 16 drops build-time linting anyway.
 */

import { dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { FlatCompat } from "@eslint/eslintrc";
import ffbeacon from "./scripts/eslint/ffbeacon-plugin.mjs";

const baseDirectory = dirname(fileURLToPath(import.meta.url));
const compat = new FlatCompat({ baseDirectory });

const config = [
  {
    ignores: [
      ".next/**",
      // Claude Code agent worktrees hold a full copy of the repo.
      ".claude/**",
      "node_modules/**",
      "public/**",
      "supabase/**",
      "docs/**",
      "next-env.d.ts",
      // Generated by the Supabase MCP; never edited by hand.
      "lib/database.types.ts",
    ],
  },
  {
    linterOptions: {
      // An eslint-disable comment that no longer suppresses anything is an
      // exception nobody needs any more; fail on it so it gets removed.
      reportUnusedDisableDirectives: "error",
    },
  },
  ...compat.extends("next/core-web-vitals", "next/typescript", "plugin:jsx-a11y/recommended"),
  {
    plugins: { ffbeacon },
    rules: {
      "ffbeacon/ascii-punctuation": "error",
      "ffbeacon/sleeper-api-host": "error",
      "ffbeacon/eastern-time": "error",

      // A leading underscore is this codebase's "deliberately unused" marker
      // (a positional parameter a signature needs, a rest-sibling omit).
      "@typescript-eslint/no-unused-vars": [
        "error",
        {
          argsIgnorePattern: "^_",
          varsIgnorePattern: "^_",
          caughtErrorsIgnorePattern: "^_",
          destructuredArrayIgnorePattern: "^_",
          ignoreRestSiblings: true,
        },
      ],

      // The rule's purpose is catching a stray > or } that was meant as code.
      // Straight apostrophes and quotes in JSX text are the house style
      // (CLAUDE.md rule 6), and escaping every one of them as &apos; protects
      // nothing.
      "react/no-unescaped-entities": ["error", { forbid: [">", "}"] }],

      // role="list" on a ul or ol is deliberate, not redundant: Safari with
      // VoiceOver drops list semantics from a list whose bullets are styled
      // away, which Tailwind's preflight does to every list.
      "jsx-a11y/no-redundant-roles": ["error", { ul: ["list"], ol: ["list"] }],

      // A scrollable table wrapper (role="region" with tabIndex 0) must be
      // focusable so a keyboard reader can scroll it (axe
      // scrollable-region-focusable), and a keyboard-explorable chart is a
      // role="group" that takes focus. The sticky side rails (aside) and raw
      // payload blocks (pre) scroll on their own for the same reason.
      "jsx-a11y/no-noninteractive-tabindex": [
        "error",
        { roles: ["tabpanel", "region", "group"], tags: ["aside", "pre"] },
      ],

      // The two "interactions" rules, recommended options with onKeyDown and
      // onKeyUp removed from the handler lists. A key listener on a container
      // is event delegation in this codebase (Escape closes a dialog or menu,
      // arrow keys move through a chart or a picker); it never makes an
      // element look clickable. Click and mouse handlers on a static or
      // non-interactive element are still errors.
      "jsx-a11y/no-static-element-interactions": [
        "error",
        {
          allowExpressionValues: true,
          handlers: ["onClick", "onMouseDown", "onMouseUp", "onKeyPress"],
        },
      ],
      "jsx-a11y/no-noninteractive-element-interactions": [
        "error",
        {
          handlers: ["onClick", "onError", "onLoad", "onMouseDown", "onMouseUp", "onKeyPress"],
          alert: ["onKeyUp", "onKeyDown", "onKeyPress"],
          body: ["onError", "onLoad"],
          dialog: ["onKeyUp", "onKeyDown", "onKeyPress"],
          iframe: ["onError", "onLoad"],
          img: ["onError", "onLoad"],
        },
      ],

      // Radio and checkbox labels here wrap the input beside a title and a
      // description in nested spans, deeper than the default search depth of 2.
      "jsx-a11y/label-has-associated-control": ["error", { depth: 5 }],

      // `role` is also an ordinary prop name on our own components
      // (PlayerLine role="in"); only DOM elements carry ARIA roles.
      "jsx-a11y/aria-role": ["error", { ignoreNonDOM: true }],
    },
  },
  {
    // Sleeper's own client is the one place allowed to name its hosts, and the
    // rule's own tests have to name them to prove it fires.
    files: ["lib/sleeper.ts", "scripts/eslint/ffbeacon-plugin.test.ts"],
    rules: { "ffbeacon/sleeper-api-host": "off" },
  },
];

export default config;
