/**
 * From an event to a card.
 *
 * Pure. It takes one stored event plus the league's CURRENT identities and
 * returns everything the component draws. No database, no clock of its own (the
 * caller fixes `nowMs`, so one page cannot say "2 hours ago" in one card and
 * "3 hours ago" in the next), and no Discord.
 *
 * THE VOICE IS THE RELAY'S VOICE, deliberately. `lib/league-relay/voice.ts` is
 * imported rather than copied, so a line here obeys the same rule every line in
 * a Discord post obeys: EVERY SENTENCE CITES A FIGURE THAT IS ON THE SAME CARD.
 * The joke is in the framing of a number, never in a claim beside it, and
 * nothing is generated by a language model. A reader has to be able to check
 * the sentence against the stat block under it.
 *
 * The draw is seeded on the event's own id, so a card reads the same on every
 * render. A feed whose wording shuffled on refresh would be unreadable, and a
 * reader who scrolled past something funny could never find it again.
 *
 * WHAT THIS FILE WILL NOT DO IS PRINT A NUMBER IT WAS NOT GIVEN. A null bench
 * total means the stat is omitted, not zeroed. A lineup change we watched
 * across a window says it was spotted, and shows the window. An approximate
 * ordering timestamp on a result is never rendered as a clock time.
 */

import { formatEastern, formatRelative } from "@/lib/datetime";
import {
  Voice,
  listOf,
  ordinal,
  type Line,
} from "@/lib/league-relay/voice";
import {
  draftStatusLabel,
  leagueStatusLabel,
  pickLabel,
  scoringLabel,
  scoringValue,
  settingLabel,
  settingValue,
  slotLabel,
} from "./labels";
import {
  ACTIVITY_CATEGORY_OF,
  type ActivityAsset,
  type ActivityCard,
  type ActivityChange,
  type ActivityChip,
  type ActivityColumn,
  type ActivityContext,
  type ActivityEvent,
  type ActivityStat,
} from "./types";

/**
 * How sharp the site's lines are allowed to be, on the relay's 0 to 1 dial.
 *
 * Lower than Discord's default of 0.8 on purpose. A Discord channel is a room
 * where people are already joking; this panel sits directly above the power
 * rankings on a page somebody opened to check their team. 0.55 keeps the
 * character and drops the lines that exist purely at a manager's expense.
 */
const SITE_SNARK = 0.55;

/* -------------------------------------------------------------------------- */
/* Entry point                                                                */
/* -------------------------------------------------------------------------- */

export function buildActivityCard(
  event: ActivityEvent,
  ctx: ActivityContext,
): ActivityCard {
  const voice = new Voice(event.id, SITE_SNARK);
  const base = emptyCard(event, ctx);

  switch (event.kind) {
    case "trade":
      return tradeCard(base, event, ctx, voice);
    case "waiver":
    case "free_agent":
    case "commissioner_move":
      // A commissioner-executed trade is stored two-sided, because a flat
      // adds/drops list cannot say which roster gave up which player. When the
      // payload has sides, it gets the two-column layout regardless of the word
      // Sleeper used for it.
      return Array.isArray(event.payload.sides)
        ? tradeCard(base, event, ctx, voice)
        : wireCard(base, event, ctx, voice);
    case "matchup_result":
      return resultCard(base, event, ctx, voice);
    case "lineup_change":
      return lineupCard(base, event, ctx, voice);
    case "reserve_move":
      return reserveCard(base, event, ctx);
    case "scoring_change":
      return scoringCard(base, event);
    case "roster_positions_change":
      return rosterSlotsCard(base, event);
    case "team_count_change":
      return teamCountCard(base, event);
    case "league_setting_change":
      return settingsCard(base, event);
    case "league_renamed":
      return renameCard(base, event);
    case "league_status_change":
      return statusCard(base, event);
    case "draft_status_change":
      return draftCard(base, event);
    case "manager_joined":
    case "manager_left":
      return managerCard(base, event, ctx);
    case "roster_owner_change":
      return ownerCard(base, event, ctx);
    case "commissioner_change":
      return commissionerCard(base, event);
    case "team_identity_change":
      return identityCard(base, event, ctx);
    default:
      return base;
  }
}

/* -------------------------------------------------------------------------- */
/* Cards                                                                      */
/* -------------------------------------------------------------------------- */

const TRADE_LINES: Line[] = [
  { heat: 0, text: "Both sides will tell you they won this one." },
  { heat: 0.2, text: "Somebody just changed their season." },
  { heat: 0.4, text: "One of these two is about to check the standings a lot." },
  { heat: 0.5, text: "Screenshotted in the league chat within the minute." },
];

function tradeCard(
  base: ActivityCard,
  event: ActivityEvent,
  ctx: ActivityContext,
  voice: Voice,
): ActivityCard {
  const sides = readSides(event.payload);
  const columns: ActivityColumn[] = sides.map((side) => {
    const chip = chipFor(ctx, side.rosterId);
    const assets: ActivityAsset[] = [
      ...side.players.map((id) => playerAsset(ctx, id, "in")),
      ...side.picks.map((p) => pickAsset(p, "in")),
    ];
    return {
      // Just "Receives". The chip directly underneath carries the team's name
      // and avatar, and repeating it in the heading printed the same words
      // twice, one line apart, on every trade card.
      heading: "Receives",
      chip,
      assets,
      faab: side.faab > 0 ? `$${side.faab} FAAB` : null,
      score: null,
      tone: "neutral",
    };
  });

  const names = sides.map((s) => chipFor(ctx, s.rosterId).label);
  const pieceCount = sides.reduce(
    (n, s) => n + s.players.length + s.picks.length + (s.faab > 0 ? 1 : 0),
    0,
  );

  const byCommissioner = event.kind === "commissioner_move";

  return {
    ...base,
    accent: byCommissioner ? "slate" : "purple",
    icon: byCommissioner ? "gavel" : "trade",
    eyebrow: byCommissioner
      ? "Commissioner move"
      : sides.length > 2
        ? `${sides.length} team trade`
        : "Trade",
    title:
      names.length > 2
        ? `${listOf(names)} made a trade`
        : names.length === 2
          ? `${names[0]} traded with ${names[1]}`
          : "Trade",
    line: !byCommissioner && pieceCount > 0 ? voice.pick(TRADE_LINES) : null,
    chips: [],
    columns,
    href: transactionsHref(ctx, event),
    hrefLabel: "Open in transactions",
  };
}

const BIG_BID_LINES: Line[] = [
  { heat: 0, text: "That is a real chunk of the budget." },
  { heat: 0.3, text: "Somebody wanted this one badly." },
  { heat: 0.5, text: "A bid placed at 2am and regretted by Thursday." },
];

function wireCard(
  base: ActivityCard,
  event: ActivityEvent,
  ctx: ActivityContext,
  voice: Voice,
): ActivityCard {
  const p = event.payload as {
    rosterId?: number | null;
    adds?: string[];
    drops?: string[];
    bid?: number | null;
  };
  const rosterId = typeof p.rosterId === "number" ? p.rosterId : null;
  const chip = rosterId != null ? chipFor(ctx, rosterId) : null;
  const adds = Array.isArray(p.adds) ? p.adds : [];
  const drops = Array.isArray(p.drops) ? p.drops : [];
  const bid = typeof p.bid === "number" && Number.isFinite(p.bid) ? p.bid : null;

  const moves: ActivityAsset[] = [
    ...adds.map((id) => playerAsset(ctx, id, "in")),
    ...drops.map((id) => playerAsset(ctx, id, "out")),
  ];

  const eyebrow =
    event.kind === "waiver"
      ? "Waiver claim"
      : event.kind === "free_agent"
        ? "Free agent move"
        : "Commissioner move";

  const who = chip?.label ?? "A team";
  const title =
    adds.length > 0 && drops.length > 0
      ? `${who} swapped ${listOf(adds.map((id) => playerName(ctx, id)))} in for ${listOf(
          drops.map((id) => playerName(ctx, id)),
        )}`
      : adds.length > 0
        ? `${who} added ${listOf(adds.map((id) => playerName(ctx, id)))}`
        : drops.length > 0
          ? `${who} dropped ${listOf(drops.map((id) => playerName(ctx, id)))}`
          : `${who} made a move`;

  const stats: ActivityStat[] = [];
  if (bid !== null) {
    stats.push({
      label: "Winning bid",
      value: bid > 0 ? `$${bid}` : "Free",
      tone: "neutral",
    });
  }

  return {
    ...base,
    accent: event.kind === "commissioner_move" ? "slate" : "cyan",
    icon:
      event.kind === "waiver"
        ? "waiver"
        : event.kind === "free_agent"
          ? "freeAgent"
          : "gavel",
    eyebrow,
    title,
    // Only fires on a bid big enough to be worth a sentence. A $1 claim gets
    // the number and no commentary, because there is nothing to say about it.
    line: bid !== null && bid >= 20 ? voice.pick(BIG_BID_LINES) : null,
    chips: chip ? [chip] : [],
    moves,
    stats,
    href: transactionsHref(ctx, event),
    hrefLabel: "Open in transactions",
  };
}

const BLOWOUT_LINES: Line[] = [
  { heat: 0, text: "Never close." },
  { heat: 0.3, text: "This one was over by the Sunday afternoon window." },
  { heat: 0.5, text: "A wellness check, not a matchup." },
];

const NAILBITER_LINES: Line[] = [
  { heat: 0, text: "Decided by less than a single carry." },
  { heat: 0.2, text: "Two managers watched the same Monday night game for very different reasons." },
  { heat: 0.4, text: "Somebody's kicker earned a Christmas card." },
];

const BENCH_LINES: Line[] = [
  { heat: 0.2, text: "The bench outscored the lineup, which is its own kind of loss." },
  { heat: 0.4, text: "The points were on the roster. They were just sitting down." },
];

function resultCard(
  base: ActivityCard,
  event: ActivityEvent,
  ctx: ActivityContext,
  voice: Voice,
): ActivityCard {
  const p = event.payload as {
    sides?: Array<{ rosterId: number; points: number; benchPoints: number | null }>;
    margin?: number;
    tie?: boolean;
  };
  const sides = Array.isArray(p.sides) ? p.sides : [];
  if (sides.length !== 2) return base;

  const tie = Boolean(p.tie);
  const margin = Number(p.margin ?? 0);
  const [top, bottom] = sides;

  const topChip = { ...chipFor(ctx, top.rosterId), tone: tie ? ("tie" as const) : ("win" as const) };
  const bottomChip = {
    ...chipFor(ctx, bottom.rosterId),
    tone: tie ? ("tie" as const) : ("loss" as const),
  };

  const columns: ActivityColumn[] = [
    {
      heading: tie ? "Tied" : "Winner",
      chip: topChip,
      assets: [],
      faab: null,
      score: points(top.points),
      tone: tie ? "tie" : "win",
    },
    {
      heading: tie ? "Tied" : "Loser",
      chip: bottomChip,
      assets: [],
      faab: null,
      score: points(bottom.points),
      tone: tie ? "tie" : "loss",
    },
  ];

  const stats: ActivityStat[] = [
    {
      label: "Margin",
      value: tie ? "Tied" : points(margin),
      tone: "neutral",
    },
  ];
  // A null bench total is Sleeper sending no per-player points for that week.
  // Omitted rather than shown as zero, which would read as a claim.
  for (const side of sides) {
    if (side.benchPoints === null) continue;
    stats.push({
      label: `${chipFor(ctx, side.rosterId).label} bench`,
      value: points(side.benchPoints),
      tone:
        side.rosterId === bottom.rosterId && side.benchPoints > margin && !tie
          ? "bad"
          : "neutral",
    });
  }

  const loserBench = bottom.benchPoints;
  const benchCostTheGame = !tie && loserBench !== null && loserBench > margin;

  const line = tie
    ? null
    : benchCostTheGame
      ? voice.pick(BENCH_LINES)
      : margin >= 30
        ? voice.pick(BLOWOUT_LINES)
        : margin <= 5
          ? voice.pick(NAILBITER_LINES)
          : null;

  const title = tie
    ? `${topChip.label} and ${bottomChip.label} tied at ${points(top.points)}`
    : `${topChip.label} beat ${bottomChip.label}, ${points(top.points)} to ${points(bottom.points)}`;

  return {
    ...base,
    accent: "emerald",
    icon: "trophy",
    eyebrow: "Final score",
    title,
    line,
    chips: [],
    columns,
    stats,
    footnote: benchCostTheGame
      ? `${bottomChip.label} left ${points(loserBench as number)} on the bench, more than the ${points(margin)} they lost by.`
      : null,
    href: matchupHref(ctx, event, top.rosterId),
    hrefLabel: "Open this matchup",
  };
}

const LINEUP_LINES: Line[] = [
  { heat: 0, text: "Lineups are still movable this week." },
  { heat: 0.3, text: "Somebody read a Wednesday practice report." },
  { heat: 0.5, text: "A decision that will look either brilliant or unforgivable by Monday." },
];

function lineupCard(
  base: ActivityCard,
  event: ActivityEvent,
  ctx: ActivityContext,
  voice: Voice,
): ActivityCard {
  const p = event.payload as { rosterId?: number; started?: string[]; benched?: string[] };
  const rosterId = typeof p.rosterId === "number" ? p.rosterId : null;
  const chip = rosterId != null ? chipFor(ctx, rosterId) : null;
  const started = Array.isArray(p.started) ? p.started : [];
  const benched = Array.isArray(p.benched) ? p.benched : [];

  const moves: ActivityAsset[] = [
    ...started.map((id) => playerAsset(ctx, id, "in")),
    ...benched.map((id) => playerAsset(ctx, id, "out")),
  ];

  const who = chip?.label ?? "A team";
  const title =
    started.length > 0 && benched.length > 0
      ? `${who} started ${listOf(started.map((id) => playerName(ctx, id)))} over ${listOf(
          benched.map((id) => playerName(ctx, id)),
        )}`
      : started.length > 0
        ? `${who} moved ${listOf(started.map((id) => playerName(ctx, id)))} into the lineup`
        : `${who} benched ${listOf(benched.map((id) => playerName(ctx, id)))}`;

  return {
    ...base,
    accent: "amber",
    icon: "lineup",
    eyebrow: "Lineup change",
    title,
    line: voice.pick(LINEUP_LINES),
    chips: chip ? [chip] : [],
    moves,
    href: teamHref(ctx, rosterId),
    hrefLabel: chip ? `Open ${chip.label}` : null,
  };
}

function reserveCard(
  base: ActivityCard,
  event: ActivityEvent,
  ctx: ActivityContext,
): ActivityCard {
  const p = event.payload as {
    rosterId?: number;
    toReserve?: string[];
    fromReserve?: string[];
    toTaxi?: string[];
    fromTaxi?: string[];
  };
  const rosterId = typeof p.rosterId === "number" ? p.rosterId : null;
  const chip = rosterId != null ? chipFor(ctx, rosterId) : null;
  const toReserve = Array.isArray(p.toReserve) ? p.toReserve : [];
  const fromReserve = Array.isArray(p.fromReserve) ? p.fromReserve : [];
  const toTaxi = Array.isArray(p.toTaxi) ? p.toTaxi : [];
  const fromTaxi = Array.isArray(p.fromTaxi) ? p.fromTaxi : [];

  const moves: ActivityAsset[] = [
    ...toReserve.map((id) => labelledAsset(ctx, id, "out", "To IR")),
    ...fromReserve.map((id) => labelledAsset(ctx, id, "in", "Off IR")),
    ...toTaxi.map((id) => labelledAsset(ctx, id, "out", "To taxi")),
    ...fromTaxi.map((id) => labelledAsset(ctx, id, "in", "Off taxi")),
  ];

  const phrases: string[] = [];
  if (toReserve.length) phrases.push(`${listOf(toReserve.map((id) => playerName(ctx, id)))} to IR`);
  if (fromReserve.length)
    phrases.push(`${listOf(fromReserve.map((id) => playerName(ctx, id)))} off IR`);
  if (toTaxi.length) phrases.push(`${listOf(toTaxi.map((id) => playerName(ctx, id)))} to the taxi squad`);
  if (fromTaxi.length)
    phrases.push(`${listOf(fromTaxi.map((id) => playerName(ctx, id)))} off the taxi squad`);

  const who = chip?.label ?? "A team";
  const title = `${who} moved ${listOf(phrases)}`;

  return {
    ...base,
    accent: "amber",
    icon: "shield",
    eyebrow: "Roster status",
    title,
    chips: chip ? [chip] : [],
    moves,
    href: teamHref(ctx, rosterId),
    hrefLabel: chip ? `Open ${chip.label}` : null,
  };
}

function scoringCard(base: ActivityCard, event: ActivityEvent): ActivityCard {
  const changes = readChanges(event.payload).map(
    (c): ActivityChange => ({
      label: scoringLabel(c.key),
      from: scoringValue(c.from),
      to: scoringValue(c.to),
      direction: direction(c.from, c.to),
    }),
  );

  return {
    ...base,
    accent: "rose",
    icon: "scoring",
    eyebrow: "Scoring settings",
    title:
      changes.length === 1
        ? `${changes[0].label} changed`
        : `${changes.length} scoring rules changed`,
    changes,
    // Not decoration. Scoring is the input to every value, projection and
    // ranking on the rest of this page, and a reader comparing a number from
    // last week to one from this week deserves to be told why they moved.
    footnote:
      "Scoring drives every projection and value on this league's pages. Numbers from before this change are not comparable with the ones after it.",
  };
}

function rosterSlotsCard(base: ActivityCard, event: ActivityEvent): ActivityCard {
  const p = event.payload as {
    added?: string[];
    removed?: string[];
    fromCount?: number;
    toCount?: number;
  };
  const added = Array.isArray(p.added) ? p.added : [];
  const removed = Array.isArray(p.removed) ? p.removed : [];

  const moves: ActivityAsset[] = [
    ...added.map((slot, i) => ({
      key: `add-${slot}-${i}`,
      label: slotLabel(slot),
      detail: "Slot added",
      position: slot,
      direction: "in" as const,
    })),
    ...removed.map((slot, i) => ({
      key: `rm-${slot}-${i}`,
      label: slotLabel(slot),
      detail: "Slot removed",
      position: slot,
      direction: "out" as const,
    })),
  ];

  const stats: ActivityStat[] = [];
  if (typeof p.fromCount === "number" && typeof p.toCount === "number") {
    stats.push({
      label: "Roster size",
      value: `${p.fromCount} to ${p.toCount}`,
      tone: "neutral",
    });
  }

  const title =
    added.length > 0 && removed.length > 0
      ? `Roster slots changed, ${added.length} added and ${removed.length} removed`
      : added.length > 0
        ? `${listOf(added.map(slotLabel))} added to every roster`
        : `${listOf(removed.map(slotLabel))} removed from every roster`;

  return {
    ...base,
    accent: "rose",
    icon: "slots",
    eyebrow: "Roster makeup",
    title,
    moves,
    stats,
    footnote:
      "Roster shape decides which positions this league actually needs, so Positional WAR and Power Pulse both rebuild from here.",
  };
}

function teamCountCard(base: ActivityCard, event: ActivityEvent): ActivityCard {
  const p = event.payload as { from?: number | null; to?: number | null };
  const from = p.from ?? null;
  const to = p.to ?? null;
  const grew = from !== null && to !== null && to > from;

  return {
    ...base,
    accent: "rose",
    icon: "teams",
    eyebrow: "League size",
    title:
      from !== null && to !== null
        ? `League went from ${from} teams to ${to}`
        : "Team count changed",
    changes: [
      {
        label: "Teams",
        from: from === null ? "Unknown" : String(from),
        to: to === null ? "Unknown" : String(to),
        direction: grew ? "up" : "down",
      },
    ],
  };
}

function settingsCard(base: ActivityCard, event: ActivityEvent): ActivityCard {
  const changes = readChanges(event.payload).map(
    (c): ActivityChange => ({
      label: settingLabel(c.key),
      from: settingValue(c.key, c.from),
      to: settingValue(c.key, c.to),
      direction: direction(c.from, c.to),
    }),
  );

  return {
    ...base,
    accent: "rose",
    icon: "settings",
    eyebrow: "League settings",
    title:
      changes.length === 1
        ? `${changes[0].label} is now ${changes[0].to}`
        : `${changes.length} league settings changed`,
    changes,
  };
}

function renameCard(base: ActivityCard, event: ActivityEvent): ActivityCard {
  const p = event.payload as { from?: string; to?: string };
  return {
    ...base,
    accent: "slate",
    icon: "rename",
    eyebrow: "League name",
    title: `League renamed to ${p.to ?? "something new"}`,
    changes: [
      {
        label: "Name",
        from: p.from ?? "Unknown",
        to: p.to ?? "Unknown",
        direction: "flat",
      },
    ],
  };
}

function statusCard(base: ActivityCard, event: ActivityEvent): ActivityCard {
  const p = event.payload as { from?: string | null; to?: string | null };
  return {
    ...base,
    accent: "slate",
    icon: "flag",
    eyebrow: "Season phase",
    title: `League is now ${leagueStatusLabel(p.to).toLowerCase()}`,
    changes: [
      {
        label: "Phase",
        from: leagueStatusLabel(p.from),
        to: leagueStatusLabel(p.to),
        direction: "flat",
      },
    ],
  };
}

function draftCard(base: ActivityCard, event: ActivityEvent): ActivityCard {
  const p = event.payload as { from?: string | null; to?: string | null };
  return {
    ...base,
    accent: "purple",
    icon: "draft",
    eyebrow: "Draft",
    title: `Draft is ${draftStatusLabel(p.to).toLowerCase()}`,
    changes: [
      {
        label: "Draft",
        from: draftStatusLabel(p.from),
        to: draftStatusLabel(p.to),
        direction: "flat",
      },
    ],
  };
}

function managerCard(
  base: ActivityCard,
  event: ActivityEvent,
  ctx: ActivityContext,
): ActivityCard {
  const p = event.payload as {
    displayName?: string | null;
    teamName?: string | null;
    rosterId?: number | null;
  };
  const joined = event.kind === "manager_joined";
  // The handle, not the team name: a team name changes on a whim and the handle
  // does not, and a manager who has just left cannot be looked up by a nickname.
  const who = p.displayName ? `@${p.displayName}` : (p.teamName ?? "A manager");
  const rosterId = typeof p.rosterId === "number" ? p.rosterId : null;
  const chip = rosterId != null ? chipFor(ctx, rosterId) : null;

  return {
    ...base,
    accent: joined ? "emerald" : "rose",
    icon: joined ? "userPlus" : "userMinus",
    eyebrow: joined ? "Manager joined" : "Manager left",
    title: joined ? `${who} joined the league` : `${who} is no longer in the league`,
    chips: chip ? [chip] : [],
    href: joined ? teamHref(ctx, rosterId) : null,
    hrefLabel: joined && chip ? `Open ${chip.label}` : null,
  };
}

function ownerCard(
  base: ActivityCard,
  event: ActivityEvent,
  ctx: ActivityContext,
): ActivityCard {
  const p = event.payload as {
    rosterId?: number;
    fromLabel?: string | null;
    toLabel?: string | null;
  };
  const rosterId = typeof p.rosterId === "number" ? p.rosterId : null;
  const chip = rosterId != null ? chipFor(ctx, rosterId) : null;
  const from = p.fromLabel ? `@${p.fromLabel}` : "an empty seat";
  const to = p.toLabel ? `@${p.toLabel}` : "nobody";

  return {
    ...base,
    accent: "amber",
    icon: "userSwap",
    eyebrow: "Team changed hands",
    title: chip
      ? `${chip.label} went from ${from} to ${to}`
      : `A roster went from ${from} to ${to}`,
    chips: chip ? [chip] : [],
    changes: [{ label: "Manager", from, to, direction: "flat" }],
    href: teamHref(ctx, rosterId),
    hrefLabel: chip ? `Open ${chip.label}` : null,
  };
}

function commissionerCard(base: ActivityCard, event: ActivityEvent): ActivityCard {
  const p = event.payload as { label?: string | null; granted?: boolean };
  const who = p.label ? `@${p.label}` : "A manager";
  const granted = Boolean(p.granted);
  return {
    ...base,
    accent: "purple",
    icon: "crown",
    eyebrow: "Commissioner",
    title: granted ? `${who} is now a commissioner` : `${who} is no longer a commissioner`,
  };
}

function identityCard(
  base: ActivityCard,
  event: ActivityEvent,
  ctx: ActivityContext,
): ActivityCard {
  const p = event.payload as {
    rosterId?: number | null;
    handle?: string | null;
    changes?: Array<{ key: string; from: unknown; to: unknown }>;
  };
  const rosterId = typeof p.rosterId === "number" ? p.rosterId : null;
  const chip = rosterId != null ? chipFor(ctx, rosterId) : null;
  const raw = Array.isArray(p.changes) ? p.changes : [];

  const changes: ActivityChange[] = raw
    // The avatar is stored as a content hash, so both sides are meaningless to
    // a reader. It is reported as a fact with no before and after.
    .filter((c) => c.key !== "avatar")
    .map((c) => ({
      label: c.key === "team_name" ? "Team name" : "Sleeper handle",
      from: asText(c.from) ?? "Not set",
      to: asText(c.to) ?? "Not set",
      direction: "flat" as const,
    }));

  const avatarChanged = raw.some((c) => c.key === "avatar");
  const who = p.handle ? `@${p.handle}` : (chip?.label ?? "A manager");

  const title =
    changes.length > 0
      ? `${who} changed ${listOf(changes.map((c) => c.label.toLowerCase()))}`
      : `${who} changed their team picture`;

  return {
    ...base,
    accent: "slate",
    icon: "tag",
    eyebrow: "Team identity",
    title,
    chips: chip ? [chip] : [],
    changes,
    footnote: avatarChanged && changes.length > 0 ? "The team picture changed too." : null,
    href: teamHref(ctx, rosterId),
    hrefLabel: chip ? `Open ${chip.label}` : null,
  };
}

/* -------------------------------------------------------------------------- */
/* Shared construction                                                        */
/* -------------------------------------------------------------------------- */

/**
 * The parts of a card that do not depend on what happened.
 *
 * Timing is settled here, once, so no card can invent its own convention. There
 * are three cases and they are genuinely different:
 *
 *   EXACT      Sleeper timestamped it. Print the time.
 *   RESULT     We know the week and nothing finer, so the week IS the time and
 *              no clock is printed at all.
 *   OBSERVED   We watched it happen inside a window. Say "spotted", and put the
 *              window itself in a note rather than picking a moment inside it.
 */
function emptyCard(event: ActivityEvent, ctx: ActivityContext): ActivityCard {
  const isResult = event.kind === "matchup_result";
  const exact = event.precision === "exact";
  // A RESULT'S TIMESTAMP IS DERIVED FROM ITS WEEK, so a game that settles before
  // its synthetic Tuesday sits slightly in the future and `formatRelative` would
  // render "in 2 days" on a card whose whole point is that the game is over.
  // The week label already says everything we actually know, so the relative
  // phrase is simply dropped rather than made up.
  const relative =
    Date.parse(event.occurredAt) > ctx.nowMs
      ? ""
      : formatRelative(event.occurredAt, ctx.nowMs);

  const timeLabel = isResult
    ? event.week != null
      ? `Week ${event.week}`
      : "Final"
    : exact
      ? formatEastern(event.occurredAt)
      : `Spotted ${formatEastern(event.occurredAt)}`;

  const timeNote =
    !exact && !isResult && event.observedFrom
      ? `Sleeper does not timestamp this kind of change, so all we can say is that it happened between ${formatEastern(
          event.observedFrom,
        )} and ${formatEastern(event.occurredAt)}.`
      : null;

  return {
    id: event.id,
    kind: event.kind,
    category: ACTIVITY_CATEGORY_OF[event.kind],
    accent: "slate",
    icon: "settings",
    eyebrow: "Activity",
    title: "Something changed",
    line: null,
    occurredAtIso: event.occurredAt,
    timeLabel,
    timeRelative: relative,
    timeNote,
    // A result puts its week in the time slot, so repeating it as a badge would
    // print "Week 6" twice on the same row.
    weekLabel: !isResult && event.week != null ? `Week ${event.week}` : null,
    chips: [],
    columns: [],
    moves: [],
    stats: [],
    changes: [],
    footnote: null,
    href: null,
    hrefLabel: null,
  };
}

function chipFor(ctx: ActivityContext, rosterId: number): ActivityChip {
  const team = ctx.teams[rosterId];
  return {
    rosterId,
    label: team?.label ?? `Team ${rosterId}`,
    owner: team?.owner ?? null,
    avatarId: team?.avatarId ?? null,
    tone: "neutral",
    href: teamHref(ctx, rosterId),
  };
}

function playerName(ctx: ActivityContext, id: string): string {
  return ctx.players[id]?.name ?? `Player ${id}`;
}

function playerAsset(
  ctx: ActivityContext,
  id: string,
  direction: "in" | "out",
): ActivityAsset {
  const p = ctx.players[id];
  // "RB, ATL" rather than a separator character. See CLAUDE.md: no middle dots.
  const detail = p
    ? [p.position, p.team].filter(Boolean).join(", ") || null
    : "Player no longer in our database";
  return {
    key: `${direction}-${id}`,
    label: p?.name ?? `Player ${id}`,
    detail,
    position: p?.position ?? null,
    direction,
  };
}

function labelledAsset(
  ctx: ActivityContext,
  id: string,
  direction: "in" | "out",
  detail: string,
): ActivityAsset {
  return { ...playerAsset(ctx, id, direction), detail };
}

function pickAsset(
  pick: { season: number; round: number; originalRosterId: number | null },
  direction: "in" | "out",
): ActivityAsset {
  return {
    key: `${direction}-pick-${pick.season}-${pick.round}-${pick.originalRosterId ?? "x"}`,
    label: pickLabel(pick.season, pick.round),
    detail: "Draft pick",
    position: "PICK",
    direction,
  };
}

/** One decimal, always, so a column of scores lines up. */
function points(value: number): string {
  return Number.isFinite(value) ? value.toFixed(1) : "0.0";
}

function direction(from: unknown, to: unknown): "up" | "down" | "flat" {
  const a = Number(from);
  const b = Number(to);
  if (!Number.isFinite(a) || !Number.isFinite(b)) return "flat";
  if (b > a) return "up";
  if (b < a) return "down";
  return "flat";
}

function asText(value: unknown): string | null {
  if (value === null || value === undefined) return null;
  const s = String(value).trim();
  return s ? s : null;
}

function readChanges(
  payload: Record<string, unknown>,
): Array<{ key: string; from: unknown; to: unknown }> {
  const raw = payload.changes;
  if (!Array.isArray(raw)) return [];
  return raw
    .filter((c): c is { key: string; from: unknown; to: unknown } => {
      return Boolean(c) && typeof (c as { key?: unknown }).key === "string";
    })
    .map((c) => ({ key: c.key, from: c.from, to: c.to }));
}

function readSides(payload: Record<string, unknown>): Array<{
  rosterId: number;
  players: string[];
  picks: Array<{ season: number; round: number; originalRosterId: number | null }>;
  faab: number;
}> {
  const raw = payload.sides;
  if (!Array.isArray(raw)) return [];
  return raw
    .map((s) => {
      const side = (s ?? {}) as Record<string, unknown>;
      const rosterId = Number(side.rosterId);
      if (!Number.isFinite(rosterId)) return null;
      return {
        rosterId,
        players: Array.isArray(side.players)
          ? side.players.filter((p): p is string => typeof p === "string")
          : [],
        picks: Array.isArray(side.picks)
          ? side.picks
              .map((p) => {
                const pick = (p ?? {}) as Record<string, unknown>;
                const season = Number(pick.season);
                const round = Number(pick.round);
                if (!Number.isFinite(season) || !Number.isFinite(round)) return null;
                const original = Number(pick.originalRosterId);
                return {
                  season,
                  round,
                  originalRosterId: Number.isFinite(original) ? original : null,
                };
              })
              .filter(
                (
                  p,
                ): p is { season: number; round: number; originalRosterId: number | null } =>
                  p !== null,
              )
          : [],
        faab: Number.isFinite(Number(side.faab)) ? Number(side.faab) : 0,
      };
    })
    .filter(
      (
        s,
      ): s is {
        rosterId: number;
        players: string[];
        picks: Array<{ season: number; round: number; originalRosterId: number | null }>;
        faab: number;
      } => s !== null,
    );
}

/* -------------------------------------------------------------------------- */
/* Links                                                                      */
/* -------------------------------------------------------------------------- */

function withUsername(path: string, ctx: ActivityContext, extra?: URLSearchParams): string {
  const qs = extra ?? new URLSearchParams();
  if (ctx.searchedUsername) qs.set("username", ctx.searchedUsername);
  const s = qs.toString();
  return s ? `${path}?${s}` : path;
}

/**
 * Where a transaction card points.
 *
 * The feed shows what moved; the transactions page shows what it was WORTH,
 * because that is where Signal Check's graded card already lives. Deliberately
 * filtered to the event's own type and week so the reader lands on a short list
 * containing their row rather than on page one of the season.
 */
function transactionsHref(ctx: ActivityContext, event: ActivityEvent): string {
  const qs = new URLSearchParams();
  // The transactions page filters on `league_transactions.type`, which is
  // Sleeper's raw string. Our kind is the same word for the four types we know
  // and is "commissioner_move" for anything else, so a card built from an
  // unrecognised type would have linked to an empty list. The payload keeps the
  // original when it differs.
  const stored =
    typeof event.payload.sleeperType === "string" && event.payload.sleeperType
      ? event.payload.sleeperType
      : null;
  const type =
    stored ?? (event.kind === "commissioner_move" ? "commissioner" : (event.kind as string));
  qs.set("type", type);
  if (event.week != null) qs.set("week", String(event.week));
  return withUsername(`/leagues/${ctx.sleeperLeagueId}/transactions`, ctx, qs);
}

function matchupHref(
  ctx: ActivityContext,
  event: ActivityEvent,
  rosterId: number,
): string | null {
  if (event.week == null) return null;
  return withUsername(
    `/leagues/${ctx.sleeperLeagueId}/schedules/${event.week}/${rosterId}`,
    ctx,
  );
}

function teamHref(ctx: ActivityContext, rosterId: number | null): string | null {
  if (rosterId == null) return null;
  return withUsername(`/leagues/${ctx.sleeperLeagueId}/teams/${rosterId}`, ctx);
}

// `ordinal` is re-exported so a future card can rank something without reaching
// into the relay's module directly.
export { ordinal };
