// Bundled emoji dataset for the Signal composer emoji picker.
//
// These are plain Unicode characters inserted into the post/comment body text.
// They are NOT catalog reactions (that is sub-phase f) and add no storage: an
// inserted emoji is just part of the body string the existing char_length CHECK
// already governs.
//
// The dataset is bundled in-app on purpose: no external CDN, no network request,
// nothing to fetch at runtime (privacy-clean). It is a curated subset, not the
// full Unicode emoji set, chosen for a fantasy-football audience. Each entry
// carries a short lowercase name used as the button's accessible label and as the
// search keyword.

export type EmojiEntry = { char: string; name: string };
export type EmojiCategory = { id: string; label: string; emojis: EmojiEntry[] };

export const EMOJI_CATEGORIES: EmojiCategory[] = [
  {
    id: "smileys",
    label: "Smileys",
    emojis: [
      { char: "😀", name: "grinning face" },
      { char: "😃", name: "grinning face with big eyes" },
      { char: "😄", name: "grinning face with smiling eyes" },
      { char: "😁", name: "beaming face with smiling eyes" },
      { char: "😆", name: "grinning squinting face" },
      { char: "😅", name: "grinning face with sweat" },
      { char: "🤣", name: "rolling on the floor laughing" },
      { char: "😂", name: "face with tears of joy" },
      { char: "🙂", name: "slightly smiling face" },
      { char: "🙃", name: "upside down face" },
      { char: "😉", name: "winking face" },
      { char: "😊", name: "smiling face with smiling eyes" },
      { char: "😇", name: "smiling face with halo" },
      { char: "😍", name: "smiling face with heart eyes" },
      { char: "🥰", name: "smiling face with hearts" },
      { char: "😘", name: "face blowing a kiss" },
      { char: "😋", name: "face savoring food" },
      { char: "😛", name: "face with tongue" },
      { char: "😜", name: "winking face with tongue" },
      { char: "🤪", name: "zany face" },
      { char: "🤨", name: "face with raised eyebrow" },
      { char: "🧐", name: "face with monocle" },
      { char: "🤓", name: "nerd face" },
      { char: "😎", name: "smiling face with sunglasses" },
      { char: "🤩", name: "star struck" },
      { char: "🥳", name: "partying face" },
      { char: "😏", name: "smirking face" },
      { char: "😒", name: "unamused face" },
      { char: "😞", name: "disappointed face" },
      { char: "😔", name: "pensive face" },
      { char: "😟", name: "worried face" },
      { char: "😤", name: "face with steam from nose" },
      { char: "😢", name: "crying face" },
      { char: "😭", name: "loudly crying face" },
      { char: "😦", name: "frowning face with open mouth" },
      { char: "😨", name: "fearful face" },
      { char: "😩", name: "weary face" },
      { char: "🤯", name: "exploding head" },
      { char: "😬", name: "grimacing face" },
      { char: "😰", name: "anxious face with sweat" },
      { char: "😱", name: "face screaming in fear" },
      { char: "🥵", name: "hot face" },
      { char: "🥶", name: "cold face" },
      { char: "😳", name: "flushed face" },
      { char: "🤬", name: "face with symbols on mouth" },
      { char: "😡", name: "enraged face" },
      { char: "😠", name: "angry face" },
      { char: "🤔", name: "thinking face" },
      { char: "🤗", name: "smiling face with open hands" },
      { char: "🤭", name: "face with hand over mouth" },
      { char: "🤫", name: "shushing face" },
      { char: "😴", name: "sleeping face" },
      { char: "🤤", name: "drooling face" },
      { char: "🤒", name: "face with thermometer" },
      { char: "🤕", name: "face with head bandage" },
      { char: "🤮", name: "face vomiting" },
      { char: "🥴", name: "woozy face" },
      { char: "😵", name: "dizzy face" },
      { char: "🤠", name: "cowboy hat face" },
      { char: "💀", name: "skull" },
      { char: "👻", name: "ghost" },
      { char: "🤡", name: "clown face" },
      { char: "💩", name: "pile of poo" },
    ],
  },
  {
    id: "gestures",
    label: "Gestures",
    emojis: [
      { char: "👍", name: "thumbs up" },
      { char: "👎", name: "thumbs down" },
      { char: "👌", name: "ok hand" },
      { char: "🤌", name: "pinched fingers" },
      { char: "✌️", name: "victory hand" },
      { char: "🤞", name: "crossed fingers" },
      { char: "🤟", name: "love you gesture" },
      { char: "🤘", name: "sign of the horns" },
      { char: "🤙", name: "call me hand" },
      { char: "👈", name: "backhand index pointing left" },
      { char: "👉", name: "backhand index pointing right" },
      { char: "👆", name: "backhand index pointing up" },
      { char: "👇", name: "backhand index pointing down" },
      { char: "☝️", name: "index pointing up" },
      { char: "✋", name: "raised hand" },
      { char: "🤚", name: "raised back of hand" },
      { char: "🖐️", name: "hand with fingers splayed" },
      { char: "🖖", name: "vulcan salute" },
      { char: "👋", name: "waving hand" },
      { char: "🤝", name: "handshake" },
      { char: "🙏", name: "folded hands" },
      { char: "✊", name: "raised fist" },
      { char: "👊", name: "oncoming fist" },
      { char: "🤛", name: "left facing fist" },
      { char: "🤜", name: "right facing fist" },
      { char: "👏", name: "clapping hands" },
      { char: "🙌", name: "raising hands" },
      { char: "👐", name: "open hands" },
      { char: "🤲", name: "palms up together" },
      { char: "💪", name: "flexed biceps" },
      { char: "🫡", name: "saluting face" },
      { char: "🫠", name: "melting face" },
      { char: "🧠", name: "brain" },
      { char: "👀", name: "eyes" },
      { char: "👑", name: "crown" },
      { char: "🔥", name: "fire" },
    ],
  },
  {
    id: "animals",
    label: "Animals",
    emojis: [
      { char: "🐶", name: "dog face" },
      { char: "🐱", name: "cat face" },
      { char: "🦁", name: "lion" },
      { char: "🐯", name: "tiger face" },
      { char: "🐴", name: "horse face" },
      { char: "🦄", name: "unicorn" },
      { char: "🐮", name: "cow face" },
      { char: "🐷", name: "pig face" },
      { char: "🐔", name: "chicken" },
      { char: "🦅", name: "eagle" },
      { char: "🦆", name: "duck" },
      { char: "🦉", name: "owl" },
      { char: "🐺", name: "wolf" },
      { char: "🐗", name: "boar" },
      { char: "🐻", name: "bear" },
      { char: "🐼", name: "panda" },
      { char: "🐨", name: "koala" },
      { char: "🐸", name: "frog" },
      { char: "🐢", name: "turtle" },
      { char: "🐍", name: "snake" },
      { char: "🦈", name: "shark" },
      { char: "🐬", name: "dolphin" },
      { char: "🐐", name: "goat" },
      { char: "🐏", name: "ram" },
      { char: "🦬", name: "bison" },
      { char: "🐝", name: "honeybee" },
      { char: "🦋", name: "butterfly" },
      { char: "🌿", name: "herb" },
      { char: "🍀", name: "four leaf clover" },
      { char: "🌎", name: "globe showing americas" },
      { char: "⭐", name: "star" },
      { char: "🌟", name: "glowing star" },
      { char: "⚡", name: "lightning" },
      { char: "❄️", name: "snowflake" },
      { char: "🌊", name: "water wave" },
    ],
  },
  {
    id: "food",
    label: "Food",
    emojis: [
      { char: "🍎", name: "red apple" },
      { char: "🍌", name: "banana" },
      { char: "🍉", name: "watermelon" },
      { char: "🍇", name: "grapes" },
      { char: "🍓", name: "strawberry" },
      { char: "🍑", name: "peach" },
      { char: "🍍", name: "pineapple" },
      { char: "🌽", name: "ear of corn" },
      { char: "🥕", name: "carrot" },
      { char: "🍔", name: "hamburger" },
      { char: "🍟", name: "french fries" },
      { char: "🍕", name: "pizza" },
      { char: "🌭", name: "hot dog" },
      { char: "🥪", name: "sandwich" },
      { char: "🌮", name: "taco" },
      { char: "🌯", name: "burrito" },
      { char: "🍗", name: "poultry leg" },
      { char: "🍖", name: "meat on bone" },
      { char: "🥓", name: "bacon" },
      { char: "🧀", name: "cheese" },
      { char: "🥨", name: "pretzel" },
      { char: "🍿", name: "popcorn" },
      { char: "🍩", name: "doughnut" },
      { char: "🍪", name: "cookie" },
      { char: "🎂", name: "birthday cake" },
      { char: "🍫", name: "chocolate bar" },
      { char: "🍺", name: "beer mug" },
      { char: "🍻", name: "clinking beer mugs" },
      { char: "🥤", name: "cup with straw" },
      { char: "☕", name: "hot beverage" },
      { char: "🧊", name: "ice" },
      { char: "🍴", name: "fork and knife" },
    ],
  },
  {
    id: "activities",
    label: "Sports",
    emojis: [
      { char: "🏈", name: "american football" },
      { char: "🏆", name: "trophy" },
      { char: "🥇", name: "first place medal" },
      { char: "🥈", name: "second place medal" },
      { char: "🥉", name: "third place medal" },
      { char: "🏅", name: "sports medal" },
      { char: "🎖️", name: "military medal" },
      { char: "🎯", name: "direct hit" },
      { char: "🏟️", name: "stadium" },
      { char: "📋", name: "clipboard" },
      { char: "📊", name: "bar chart" },
      { char: "📈", name: "chart increasing" },
      { char: "📉", name: "chart decreasing" },
      { char: "⏱️", name: "stopwatch" },
      { char: "🚑", name: "ambulance" },
      { char: "🩹", name: "adhesive bandage" },
      { char: "💰", name: "money bag" },
      { char: "💵", name: "dollar banknote" },
      { char: "🤑", name: "money mouth face" },
      { char: "⚽", name: "soccer ball" },
      { char: "🏀", name: "basketball" },
      { char: "⚾", name: "baseball" },
      { char: "🏒", name: "ice hockey" },
      { char: "🎮", name: "video game" },
      { char: "🎲", name: "game die" },
      { char: "🃏", name: "joker" },
      { char: "🎉", name: "party popper" },
      { char: "🎊", name: "confetti ball" },
      { char: "🔔", name: "bell" },
      { char: "📣", name: "megaphone" },
    ],
  },
  {
    id: "travel",
    label: "Travel",
    emojis: [
      { char: "🚗", name: "automobile" },
      { char: "🚕", name: "taxi" },
      { char: "🚌", name: "bus" },
      { char: "🏎️", name: "racing car" },
      { char: "🚓", name: "police car" },
      { char: "🚒", name: "fire engine" },
      { char: "✈️", name: "airplane" },
      { char: "🚀", name: "rocket" },
      { char: "🛸", name: "flying saucer" },
      { char: "🚁", name: "helicopter" },
      { char: "⛵", name: "sailboat" },
      { char: "🚢", name: "ship" },
      { char: "🏠", name: "house" },
      { char: "🏢", name: "office building" },
      { char: "🗽", name: "statue of liberty" },
      { char: "🌉", name: "bridge at night" },
      { char: "🗺️", name: "world map" },
      { char: "🧭", name: "compass" },
      { char: "🏝️", name: "desert island" },
      { char: "🏕️", name: "camping" },
    ],
  },
  {
    id: "objects",
    label: "Objects",
    emojis: [
      { char: "📱", name: "mobile phone" },
      { char: "💻", name: "laptop" },
      { char: "⌚", name: "watch" },
      { char: "📷", name: "camera" },
      { char: "🎥", name: "movie camera" },
      { char: "📺", name: "television" },
      { char: "🎧", name: "headphone" },
      { char: "📻", name: "radio" },
      { char: "🔋", name: "battery" },
      { char: "💡", name: "light bulb" },
      { char: "🔦", name: "flashlight" },
      { char: "📚", name: "books" },
      { char: "📝", name: "memo" },
      { char: "✏️", name: "pencil" },
      { char: "📌", name: "pushpin" },
      { char: "📎", name: "paperclip" },
      { char: "🔑", name: "key" },
      { char: "🔒", name: "locked" },
      { char: "🔓", name: "unlocked" },
      { char: "🛡️", name: "shield" },
      { char: "🔍", name: "magnifying glass" },
      { char: "⏰", name: "alarm clock" },
      { char: "🧨", name: "firecracker" },
      { char: "🎁", name: "wrapped gift" },
    ],
  },
  {
    id: "symbols",
    label: "Symbols",
    emojis: [
      { char: "❤️", name: "red heart" },
      { char: "🧡", name: "orange heart" },
      { char: "💛", name: "yellow heart" },
      { char: "💚", name: "green heart" },
      { char: "💙", name: "blue heart" },
      { char: "💜", name: "purple heart" },
      { char: "🖤", name: "black heart" },
      { char: "💔", name: "broken heart" },
      { char: "💯", name: "hundred points" },
      { char: "💢", name: "anger symbol" },
      { char: "💥", name: "collision" },
      { char: "💫", name: "dizzy" },
      { char: "💦", name: "sweat droplets" },
      { char: "✅", name: "check mark button" },
      { char: "❌", name: "cross mark" },
      { char: "❓", name: "question mark" },
      { char: "❗", name: "exclamation mark" },
      { char: "⚠️", name: "warning" },
      { char: "🚫", name: "prohibited" },
      { char: "➕", name: "plus" },
      { char: "➖", name: "minus" },
      { char: "✔️", name: "check mark" },
      { char: "🆗", name: "ok button" },
      { char: "🆕", name: "new button" },
      { char: "🔝", name: "top arrow" },
      { char: "🔻", name: "red triangle pointed down" },
      { char: "🔺", name: "red triangle pointed up" },
      { char: "♻️", name: "recycling symbol" },
      { char: "🏳️", name: "white flag" },
      { char: "🏴", name: "black flag" },
      { char: "🚩", name: "triangular flag" },
    ],
  },
];

/** Flat list of every bundled emoji, used by the picker's search filter. */
export const ALL_EMOJI: EmojiEntry[] = EMOJI_CATEGORIES.flatMap((c) => c.emojis);
