/**
 * The relay's voice.
 *
 * The brief is a writeup, not a bullet list: sarcastic, hyperbolic, funny, and
 * still worth reading for the numbers. Those two goals fight, and the way this
 * module settles the fight is the only interesting thing in it:
 *
 *   EVERY SENTENCE CITES A FIGURE THAT IS ON THE SAME SCREEN. The joke is in
 *   the FRAMING of the number, never in a claim beside it. "Wow, this team
 *   sucks" is not sayable on its own; "the worst projected lineup in the
 *   league, 14.2 points behind eleventh" is, and it is funnier for being true.
 *
 *   NOTHING HERE IS GENERATED BY A LANGUAGE MODEL. Same rule as Signal Check's
 *   reasons (see CLAUDE.md, Trade Ideas): a reader must be able to check every
 *   sentence against the numbers printed under it, which a generated one does
 *   not allow. These are hand-written templates chosen by a seeded draw.
 *
 * WHY THE DRAW IS SEEDED. The same trade must read the same way every time it
 * is rendered: the admin preview has to show what the channel will get, a retry
 * after a Discord 500 must not post a differently-worded second version, and a
 * ledger row has to match what went out. So the seed is the message's own
 * dedupe key, and variety comes from there being many keys, not from a clock.
 *
 * SNARK IS A DIAL, NOT A SWITCH. `snark` runs 0 to 1. Each line carries the
 * heat it needs; a line hotter than the setting is simply not drawn, so turning
 * the dial down yields a straight report built from the same figures rather
 * than a different feature.
 */

/** A line, and how sharp it is. Drawn only when `snark` is at least `heat`. */
export interface Line {
  /** 0 is a neutral statement of fact. 1 is at somebody's expense. */
  heat: number;
  text: string;
}

/* -------------------------------------------------------------------------- */
/* Seeded selection                                                           */
/* -------------------------------------------------------------------------- */

/** FNV-1a. Small, fast, and stable across runtimes, which is the requirement. */
export function seedFrom(key: string): number {
  let h = 0x811c9dc5;
  for (let i = 0; i < key.length; i += 1) {
    h ^= key.charCodeAt(i);
    h = Math.imul(h, 0x01000193);
  }
  return h >>> 0;
}

/**
 * A deterministic draw over a seed.
 *
 * mulberry32: one line of arithmetic, uniform enough for choosing between eight
 * phrasings, and identical on every machine. `Math.random` would break the
 * guarantee in the header.
 */
export function makeRng(seed: number): () => number {
  let a = seed >>> 0;
  return () => {
    a = (a + 0x6d2b79f5) >>> 0;
    let t = a;
    t = Math.imul(t ^ (t >>> 15), t | 1);
    t ^= t + Math.imul(t ^ (t >>> 7), t | 61);
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

/**
 * A writer, bound to one message.
 *
 * Holds the seed and the snark setting so a builder can ask for a line without
 * threading either through every call.
 */
export class Voice {
  private rng: () => number;
  /**
   * Every line this writer has already used.
   *
   * A message describes two teams, and the two draws are independent, so
   * nothing stopped both of them landing on the same phrase. The first real run
   * produced a preview whose two closing lines were "actively bad in a way that
   * is starting to look deliberate", twice, one under the other. That does not
   * read as a coincidence, it reads as a broken template.
   */
  private used = new Set<string>();

  constructor(
    seedKey: string,
    /** 0 to 1. */
    public readonly snark: number,
  ) {
    this.rng = makeRng(seedFrom(seedKey));
  }

  /** A number in [0, 1). Advances the sequence, so call order matters. */
  next(): number {
    return this.rng();
  }

  /**
   * Draw one line from a bank, honouring the snark setting.
   *
   * Lines hotter than the setting are filtered out FIRST, so lowering the dial
   * changes which lines are eligible rather than merely how often a hot one is
   * picked. Returns null when the bank has nothing cool enough, which is a
   * legitimate outcome: the section is simply not written.
   *
   * A line already used in this message is skipped, unless skipping would leave
   * nothing at all. Repeating beats staying silent; repeating by accident does
   * not.
   */
  pick(bank: Line[]): string | null {
    const eligible = bank.filter((l) => l.heat <= this.snark);
    if (eligible.length === 0) return null;
    const unused = eligible.filter((l) => !this.used.has(l.text));
    const pool = unused.length > 0 ? unused : eligible;
    const chosen = pool[Math.floor(this.rng() * pool.length)].text;
    this.used.add(chosen);
    return chosen;
  }

  /** Draw from a plain list of strings, all at heat 0. */
  pickPlain(bank: string[]): string {
    const unused = bank.filter((t) => !this.used.has(t));
    const pool = unused.length > 0 ? unused : bank;
    const chosen = pool[Math.floor(this.rng() * pool.length)];
    this.used.add(chosen);
    return chosen;
  }
}

/* -------------------------------------------------------------------------- */
/* Number formatting the writeups share                                       */
/* -------------------------------------------------------------------------- */

export function pct(value: number | null | undefined, digits = 0): string | null {
  if (value === null || value === undefined || !Number.isFinite(value)) return null;
  return `${(value * 100).toFixed(digits)}%`;
}

/** A signed percentage-point change: "+12 points", "-4 points". */
export function ppChange(
  before: number | null | undefined,
  after: number | null | undefined,
): { text: string; delta: number } | null {
  if (before === null || before === undefined || after === null || after === undefined) return null;
  if (!Number.isFinite(before) || !Number.isFinite(after)) return null;
  const delta = (after - before) * 100;
  if (Math.abs(delta) < 0.5) return { text: "no meaningful change", delta: 0 };
  const sign = delta > 0 ? "+" : "";
  return { text: `${sign}${delta.toFixed(0)} points`, delta };
}

export function signed(value: number, digits = 1): string {
  const sign = value > 0 ? "+" : value < 0 ? "" : "";
  return `${sign}${value.toFixed(digits)}`;
}

export function num(value: number | null | undefined, digits = 1): string | null {
  if (value === null || value === undefined || !Number.isFinite(value)) return null;
  return value.toFixed(digits);
}

/** "1st", "2nd", "11th". Used for every rank in every writeup. */
export function ordinal(n: number): string {
  const abs = Math.abs(Math.round(n));
  const last2 = abs % 100;
  if (last2 >= 11 && last2 <= 13) return `${abs}th`;
  switch (abs % 10) {
    case 1:
      return `${abs}st`;
    case 2:
      return `${abs}nd`;
    case 3:
      return `${abs}rd`;
    default:
      return `${abs}th`;
  }
}

/** "Mahomes and Kelce", "Mahomes, Kelce and a 2027 1st". Never an oxford comma. */
export function listOf(items: string[]): string {
  if (items.length === 0) return "nothing";
  if (items.length === 1) return items[0];
  if (items.length === 2) return `${items[0]} and ${items[1]}`;
  return `${items.slice(0, -1).join(", ")} and ${items[items.length - 1]}`;
}

/* -------------------------------------------------------------------------- */
/* Banded openers                                                             */
/* -------------------------------------------------------------------------- */

/**
 * How a team is doing, in five bands, from its rank within its own league.
 *
 * A rank rather than a raw score, because a 78 Power Pulse is excellent in one
 * league and mid-table in another, and the reader only cares about the room
 * they are in.
 */
export type Band = "elite" | "good" | "middle" | "poor" | "dire";

export function bandFromRank(rank: number | null, total: number): Band {
  if (rank === null || total <= 1) return "middle";
  const q = (rank - 1) / (total - 1);
  if (q <= 0.15) return "elite";
  if (q <= 0.4) return "good";
  if (q <= 0.6) return "middle";
  if (q <= 0.85) return "poor";
  return "dire";
}

/**
 * A short, honest adjective for a band. The straight version, used wherever a
 * sentence needs the fact rather than the joke.
 */
export const BAND_PLAIN: Record<Band, string> = {
  elite: "one of the best teams in the league",
  good: "a solid playoff side",
  middle: "a mid-table team",
  poor: "a team in trouble",
  dire: "the worst team in the league",
};

/**
 * The hyperbolic version.
 *
 * These are the "wow, this team sucks" lines the brief asked for. Every one of
 * them is an opinion about a RANK the reader can see, so the hyperbole sits on
 * top of a fact rather than replacing one.
 */
export const BAND_LINES: Record<Band, Line[]> = {
  elite: [
    { heat: 0.3, text: "genuinely frightening" },
    { heat: 0.6, text: "an unfair roster assembled by an unwell person" },
    { heat: 0.6, text: "the reason three managers have stopped opening the app" },
    { heat: 0.9, text: "so far ahead it has become a moral problem" },
  ],
  good: [
    { heat: 0.3, text: "quietly excellent" },
    { heat: 0.5, text: "good in the boring way that wins titles" },
    { heat: 0.7, text: "one injury away from being insufferable about it" },
  ],
  middle: [
    { heat: 0.3, text: "aggressively fine" },
    { heat: 0.5, text: "a team with no discernible plan and no obvious flaw" },
    { heat: 0.7, text: "the fantasy equivalent of a beige rental car" },
  ],
  poor: [
    { heat: 0.4, text: "not good, and the numbers agree" },
    { heat: 0.6, text: "a roster held together by optimism and one good tight end" },
    { heat: 0.8, text: "actively bad in a way that is starting to look deliberate" },
  ],
  dire: [
    { heat: 0.4, text: "the worst team here, by some distance" },
    { heat: 0.7, text: "a catastrophe with a logo" },
    { heat: 0.9, text: "so bad it is arguably a rebuilding strategy" },
    { heat: 0.9, text: "an argument for contraction" },
  ],
};

/**
 * The band as a phrase, with the hyperbole applied when the dial allows it and
 * the plain adjective when it does not. Never returns nothing: every writeup
 * needs to be able to describe a team.
 */
export function describeBand(voice: Voice, band: Band): string {
  return voice.pick(BAND_LINES[band]) ?? BAND_PLAIN[band];
}

/* -------------------------------------------------------------------------- */
/* Shared openers                                                             */
/* -------------------------------------------------------------------------- */

/** How a trade writeup can open. The subject follows, so these all trail off. */
export const TRADE_OPENERS: Line[] = [
  { heat: 0, text: "A trade has landed." },
  { heat: 0.3, text: "Somebody pressed accept." },
  { heat: 0.4, text: "Well. That happened." },
  { heat: 0.5, text: "Against all advice, a trade has been agreed." },
  { heat: 0.6, text: "Two managers looked at the same numbers and reached opposite conclusions." },
  { heat: 0.7, text: "The league chat is about to get busy." },
];

/** How a lopsided verdict can be introduced. */
export const LOPSIDED_LINES: Line[] = [
  { heat: 0.2, text: "This one is not close." },
  { heat: 0.5, text: "Calling this a negotiation is generous." },
  { heat: 0.7, text: "Somebody has been robbed in broad daylight." },
  { heat: 0.8, text: "This is less a trade than a donation with extra steps." },
];

/** How an even verdict can be introduced. */
export const EVEN_LINES: Line[] = [
  { heat: 0.2, text: "For once, both sides have a case." },
  { heat: 0.4, text: "Disappointingly reasonable from everyone involved." },
  { heat: 0.6, text: "Two adults negotiated in good faith, which is frankly out of character." },
];

/** Closers for a matchup preview. */
export const PREVIEW_CLOSERS: Line[] = [
  { heat: 0, text: "Lineups lock Sunday. Set them." },
  { heat: 0.3, text: "Set your lineup. Or do not, and provide content." },
  { heat: 0.5, text: "Somebody is going to start a player on bye. It is always somebody." },
  { heat: 0.6, text: "One of these managers will blame the projections by Monday." },
];

/** Closers for a matchup recap. */
export const RECAP_CLOSERS: Line[] = [
  { heat: 0, text: "On to next week." },
  { heat: 0.3, text: "That result is now permanent. Sorry." },
  { heat: 0.5, text: "The standings do not care how it felt." },
  { heat: 0.7, text: "Screenshot it, frame it, never speak of it again." },
];
