/**
 * The sentences.
 *
 * Every number this feature produces is already on the card. These lines exist
 * because a column of deltas does not tell a manager whether to send the offer,
 * and because the person this site is built for is listening to the page rather
 * than scanning it. A screen reader user should be able to hear the headline,
 * hear one sentence about their own side, hear one about the other team, and
 * know enough to decide.
 *
 * Nothing here is generated by a model and nothing here is invented. Each
 * sentence is assembled from figures the engine computed, and when a figure is
 * missing the sentence that would have used it is dropped rather than softened
 * into something vague. A caveat list carries what would otherwise make a number
 * misleading.
 */

import { RANK_THRESHOLDS } from "./rank";
import { NAMEABLE_WINS } from "./pulse";
import { TENDENCY_DEFAULTS } from "./tendency";
import type { TendencySlice } from "@/lib/manager-pulse/types";
import type {
  SideImpact,
  SuggestionAsset,
  TeamDirection,
  TradeGoal,
  TradePosition,
  TradeStrategy,
} from "./types";

/** How the reader described what they were after, in the engine's own words. */
const GOAL_CLAUSE: Record<TradeGoal, string> = {
  balanced: "You did not narrow the search, so this is the best deal on the board.",
  consolidate: "You asked to consolidate, and this is that shape of deal.",
  "split-assets": "You asked to split an asset up, and this is that shape of deal.",
  "add-picks": "You asked for draft capital, and this is that shape of deal.",
  "get-younger": "You asked to get younger, and this is that shape of deal.",
};

/**
 * The opening clause when the reader has not narrowed the search but Power
 * Pulse has an opinion about their season.
 *
 * This is the sentence that says the ranking is not the same for everybody.
 * A contender and a rebuilder pressing the same button get different deals
 * now, and a reader who is not told that has no way to know why the tool
 * stopped offering them draft picks. It replaces the generic goal clause
 * rather than joining it, because both would be answering the same question.
 *
 * Only for the balanced goal. A reader who picked "Obtain draft picks" asked a
 * narrower question than their standing, and the goal clause is the honest
 * account of why they are seeing what they are seeing.
 */
/**
 * The opener in a one-year league, whatever the reader's standing says.
 *
 * A redraft league has one timeline, so the Contender / Rebuilder split has
 * nothing to say about it and the dynasty clauses below would say the wrong
 * thing: a team at the bottom of a redraft table reads as win-now inside the
 * engine (see lib/trade-finder/profile.ts), and telling that reader "Power
 * Pulse has you competing" is not what they see on the standings page.
 */
const REDRAFT_CLAUSE =
  "This is a one-year league, so the ranking is about what a deal does to your lineup rather than what an asset holds for later.";

/**
 * The opener when the reader has told us which question they are asking.
 *
 * This outranks the stance clause below, and the reason is the same one that
 * makes the strategy replace the stance multipliers in the ranking: the stance
 * clause reports an inference about the reader, and this reports a statement by
 * them. Telling somebody who has just pressed Value that "Power Pulse has you
 * competing, so this leans on lineup points" describes a ranking that is not the
 * one they are looking at.
 *
 * Dynasty only. A redraft league has its own opener, because there the strategy
 * was never a choice and phrasing it as one would invite a reader to go looking
 * for the toggle that turns it off.
 */
const STRATEGY_CLAUSE: Record<TradeStrategy, string> = {
  // Both kept under ninety characters, matching STANCE_CLAUSE below, and for
  // the reason stated there: three clauses share a 360 character ceiling and a
  // long opener is paid for by the sentence at the END, which is the one naming
  // the reader's actual hole. The first drafts ran to 133 and 118, and against
  // a long team name the contender one truncated that sentence mid-word.
  contender:
    "You asked for contender deals, so this ranking leads on lineup points and projected wins.",
  value:
    "You asked for value deals, so this ranking leads on what the pieces are worth.",
};

const STANCE_CLAUSE: Record<TeamDirection, string | null> = {
  // Kept short. Three clauses share a 360 character ceiling, and a team name in
  // this league can run long, so an opener that runs to 130 characters is what
  // pushes the sentence that names the reader's actual hole off the end.
  "win-now":
    "Power Pulse has you competing, so this ranking leans on lineup points and projected wins.",
  rebuild:
    "Power Pulse has you out of the race, so this ranking leans on value and youth rather than this Sunday.",
  // A team in the pack genuinely wants both, and saying so adds nothing the
  // deltas below do not already say.
  balanced: null,
};

/**
 * Ceiling on the finished sentence.
 *
 * The saved-trade schema caps every text field at 400 characters, and a bookmark
 * that fails to save because a team name was long is a failure the reader can do
 * nothing about and would not understand. Kept comfortably under it.
 */
const MAX_RATIONALE = 360;

/** "Bijan Robinson", "Bijan Robinson and a 2027 1st", "A, B, and C". */
export function listAssets(assets: SuggestionAsset[]): string {
  const names = assets.map((a) => (a.kind === "player" ? a.name : a.label));
  if (names.length === 0) return "nothing";
  if (names.length === 1) return names[0];
  if (names.length === 2) return `${names[0]} and ${names[1]}`;
  return `${names.slice(0, -1).join(", ")}, and ${names[names.length - 1]}`;
}

/**
 * At or under this many games left, the season itself is the limit on what a
 * trade can do, and the card says so.
 */
const LATE_SEASON_GAMES = 3;

/** Points per week, signed, to one decimal. */
function points(delta: number): string {
  const rounded = Math.abs(delta).toFixed(1);
  return `${delta >= 0 ? "+" : "-"}${rounded}`;
}

function round(value: number): string {
  return Math.round(Math.abs(value)).toLocaleString("en-US");
}

/** "a receiver", "a receiver or a tight end", "a back, a receiver, or a tight end". */
function orList(words: string[]): string {
  if (words.length === 1) return words[0];
  if (words.length === 2) return `${words[0]} or ${words[1]}`;
  return `${words.slice(0, -1).join(", ")}, or ${words[words.length - 1]}`;
}

/**
 * The opening clause when the reader named positions rather than a player.
 *
 * Written as the request read back, so the first thing on the card confirms the
 * control did something. Both halves when both were set, because a reader who
 * asked to move a back for a receiver is asking one question, not two.
 */
function askClause(want: string[], give: string[]): string {
  if (want.length > 0 && give.length > 0) {
    return `You asked to bring in ${orList(want)} and move ${orList(give)}.`;
  }
  if (want.length > 0) return `You asked to bring in ${orList(want)}.`;
  return `You asked to move ${orList(give)}.`;
}

export function buildHeadline(
  incoming: SuggestionAsset[],
  outgoing: SuggestionAsset[],
  teamName: string,
): string {
  return `Send ${listAssets(outgoing)} to ${teamName} for ${listAssets(incoming)}.`;
}

/**
 * Why this deal is being shown at all.
 *
 * Every other sentence on the card describes the deal. This one describes the
 * SEARCH, and it is here because a suggestion engine that will not say why it
 * chose something reads as arbitrary, which is the single most common thing
 * managers said about the portfolio surface: four leagues in, four deals out, no
 * account of what made any of them the one to show.
 *
 * Three clauses at most, each of which is a fact the engine already established:
 * the shape the reader asked for, the counterparty's own situation that put the
 * piece within reach, and the measured hole on the reader's roster it lands in.
 * A clause with nothing true behind it is dropped rather than padded, so this
 * can be one sentence or three, and the shortest version is still honest.
 *
 * The league name is deliberately absent. On the league tab it is the page, and
 * on the portfolio panel the card already carries it as a chip, so repeating it
 * here would be the same word twice in two lines.
 */
export function buildRationale(params: {
  /** The shape constraint, when the caller set one. Defaults to "any". */
  goal?: TradeGoal;
  /**
   * What the counterparty's roster is pointing at.
   *
   * The status LABEL is deliberately not taken. The card already carries it as a
   * chip two lines above ("They are a Rebuilder"), and restating it here made a
   * screen reader announce the same fact twice within a breath. The direction
   * carries the same information and this sentence spends it on the consequence
   * instead, which is the part the chip cannot say.
   */
  direction: TeamDirection;
  teamName: string;
  /** The position the reader's lineup measurably gains at, when there is one. */
  positionHelped: string | null;
  /** Points per week that position was short by. */
  needPoints: number | null;
  /** Whether the deal was built around players the reader named, and which side. */
  named: "target" | "offer" | null;
  /**
   * How many players the reader pinned to that side. Drives singular versus
   * plural, so a package of three does not read as "the player you named".
   */
  namedCount?: number;
  /**
   * The READER's own footing, which is what the ranking was weighted by.
   *
   * Distinct from `direction` above, which is the counterparty's. Both appear
   * in this sentence and they are routinely opposite, which is exactly why a
   * deal exists at all.
   */
  myDirection?: TeamDirection;
  /**
   * Whether assets carry past this season.
   *
   * Outranks `myDirection` in the opening clause, because in a one-year league
   * the direction is win-now for everybody by construction and saying so back
   * to a reader sitting last would read as a bug.
   */
  isDynasty?: boolean;
  /**
   * Which question the ranking was answering. See STRATEGY_CLAUSE.
   *
   * Absent for a caller that has not set one, which falls back to the reader's
   * own footing exactly as it did before the toggle existed.
   */
  strategy?: TradeStrategy | null;
  /**
   * Position groups the reader asked for, if any, as plain words.
   *
   * The opening clause names what was ASKED FOR rather than the goal whenever
   * there is an ask, because a reader who set a filter and reads "a deal that
   * fits how your roster is built" has no way to tell whether the filter did
   * anything. Empty arrays mean no ask on that side, and the clause falls back.
   */
  asked?: { want: string[]; give: string[] } | null;
  mine: SideImpact;
}): string {
  const parts: string[] = [];

  const wanted = params.asked?.want ?? [];
  const given = params.asked?.give ?? [];

  const count = params.namedCount ?? 1;
  if (params.named === "target") {
    parts.push(
      count > 1
        ? "This is what it would take to get the players you named, together."
        : "This is what it would take to get the player you named.",
    );
  } else if (params.named === "offer") {
    parts.push(
      count > 1
        ? "This is what the players you named bring back as a package."
        : "This is what the player you named brings back.",
    );
  } else if (wanted.length > 0 || given.length > 0) {
    parts.push(askClause(wanted, given));
  } else {
    // The reader's own standing outranks the generic "you did not narrow the
    // search" line, because it says something true and specific about why THIS
    // deal is on top rather than merely confirming that no filter was set.
    const goal = params.goal ?? "balanced";
    const stance =
      goal !== "balanced"
        ? null
        : params.isDynasty === false
          ? REDRAFT_CLAUSE
          : params.strategy === "contender" || params.strategy === "value"
            ? // Branched rather than indexed. The value is validated twice
              // before it gets here, so this is belt and braces, but an object
              // literal answers "__proto__" with something truthy and that
              // would put "[object Object]" into a sentence on a card.
              STRATEGY_CLAUSE[params.strategy]
            : params.myDirection
              ? STANCE_CLAUSE[params.myDirection]
              : null;
    parts.push(stance ?? GOAL_CLAUSE[goal] ?? GOAL_CLAUSE.balanced);
  }

  // Why THIS team. A manager's willingness is the part a reader cannot see from
  // their own roster, and it is the reason one counterparty came up over ten
  // others who own comparable players.
  //
  // Every branch is a complete sentence in both shapes. The first version built
  // one out of a noun phrase that only had a verb in it when a status label
  // existed, and a league with no Power Pulse row got "Bob's Bombers with no
  // strong pull either way, which is who tends to answer." On a page a fragment
  // skims past. Read aloud, which is how this site is used, it lands as a glitch
  // and the listener backs up.
  const team = params.teamName;
  if (params.direction === "rebuild") {
    parts.push(
      `${team} are rebuilding, so the pieces they would move are the ones with a shelf life.`,
    );
  } else if (params.direction === "win-now") {
    parts.push(
      `${team} are chasing this season, so what they can spare is the depth behind their starters.`,
    );
  } else {
    parts.push(
      `${team} have no strong pull either way, which is the kind of team that tends to answer.`,
    );
  }

  if (
    params.positionHelped &&
    params.needPoints !== null &&
    params.needPoints > 0
  ) {
    // "short at X" rather than "thinnest at X". The engine measured the need at
    // the positions this deal actually brings in, not across the whole roster,
    // so calling it the thinnest spot would be a claim it never established.
    parts.push(
      `Your lineup is short at ${params.positionHelped}, about ${params.needPoints.toFixed(1)} points a week behind, and this deal lands there.`,
    );
  } else if (params.mine.pickCountDelta > 0) {
    parts.push(
      `It brings back ${params.mine.pickCountDelta} draft ${params.mine.pickCountDelta === 1 ? "pick" : "picks"}.`,
    );
  }

  const sentence = parts.join(" ");
  return sentence.length <= MAX_RATIONALE
    ? sentence
    : `${sentence.slice(0, MAX_RATIONALE - 1).trimEnd()}.`;
}

/**
 * The reader's side.
 *
 * Lineup change leads whenever we have one, because it is the part that happens
 * on Sunday. Value follows, and it is phrased as a gap rather than a verdict:
 * "you give up a little value" is the truth, and calling the same trade a loss
 * would misread a deal that turns a bench player into a starter.
 */
export function buildWhyYou(
  mine: SideImpact,
  goal: TradeGoal | undefined,
  positionHelped: string | null,
): string {
  const parts: string[] = [];

  if (mine.lineupDelta !== null && Math.abs(mine.lineupDelta) >= 0.1) {
    const where = positionHelped ? ` at ${positionHelped}` : "";
    parts.push(
      mine.lineupDelta > 0
        ? `Your starting lineup gains ${points(mine.lineupDelta)} points a week${where}.`
        : `Your starting lineup gives up ${points(mine.lineupDelta)} points a week${where}.`,
    );
  }

  // What those points are worth in games, against the schedule this team
  // actually has left. Called an estimate out loud, because it is a
  // linearization of the Power Pulse season rather than a rerun of it, and the
  // full simulation is one press away in the builder.
  if (mine.winsDelta !== null && Math.abs(mine.winsDelta) >= NAMEABLE_WINS) {
    const size = Math.abs(mine.winsDelta);
    // "1.35 of a projected win" is not a sentence. Under one it is a fraction
    // of a win and reads as one; at or over one it is a count.
    const amount =
      size < 1
        ? `${size.toFixed(2)} of a projected win`
        : `${size.toFixed(2)} projected wins`;
    parts.push(
      mine.winsDelta > 0
        ? `Against your remaining schedule that is worth about ${amount}.`
        : `Against your remaining schedule that costs about ${amount}.`,
    );
  }

  if (Math.abs(mine.valueDelta) >= 1) {
    parts.push(
      mine.valueDelta > 0
        ? `You come out ${round(mine.valueDelta)} points of trade value ahead.`
        : `You give up ${round(mine.valueDelta)} points of trade value to do it.`,
    );
  } else {
    parts.push("The two sides are level on trade value.");
  }

  if (goal === "get-younger" && mine.ageDelta !== null && mine.ageDelta < 0) {
    parts.push(`Your roster gets ${Math.abs(mine.ageDelta).toFixed(1)} years younger on average.`);
  }
  if (goal === "add-picks" && mine.pickCountDelta > 0) {
    parts.push(
      `You add ${mine.pickCountDelta} draft ${mine.pickCountDelta === 1 ? "pick" : "picks"}.`,
    );
  }

  return parts.join(" ");
}

/**
 * The other manager's side.
 *
 * Written from their situation rather than ours, because that is the argument
 * the reader has to make in the league chat. If the honest answer is that the
 * deal only works for us, the sentence says so instead of dressing it up.
 */
export function buildWhyThem(
  theirs: SideImpact,
  direction: TeamDirection,
  teamName: string,
  statusLabel: string | null,
): string {
  const who = statusLabel ? `${teamName} reads as a ${statusLabel.toLowerCase()}` : teamName;
  const parts: string[] = [];

  // The same bar the acceptance band uses. Arguing "it makes them younger" off a
  // tenth of a year would be an argument the rest of the engine does not credit,
  // and a reader who repeats it in their league chat gets asked how much younger.
  const meaningfullyYounger =
    theirs.ageDelta !== null && theirs.ageDelta < -RANK_THRESHOLDS.MEANINGFULLY_YOUNGER;

  if (direction === "rebuild") {
    if (theirs.pickCountDelta > 0) {
      parts.push(
        `${who}, and this hands them ${theirs.pickCountDelta} more draft ${theirs.pickCountDelta === 1 ? "pick" : "picks"} for a season they are not winning.`,
      );
    } else if (meaningfullyYounger) {
      parts.push(
        `${who}, and this takes ${Math.abs(theirs.ageDelta as number).toFixed(1)} years off their average age.`,
      );
    } else {
      parts.push(`${who}, so the case has to be the value.`);
    }
  } else if (direction === "win-now") {
    if (theirs.lineupDelta !== null && theirs.lineupDelta > 0) {
      parts.push(
        `${who} chasing this season, and this adds ${points(theirs.lineupDelta)} points a week to their starting lineup.`,
      );
    } else {
      parts.push(`${who} chasing this season, so the case has to be the value.`);
    }
  } else {
    parts.push(
      theirs.lineupDelta !== null && theirs.lineupDelta > 0
        ? `${who} in the middle of the pack, and this adds ${points(theirs.lineupDelta)} points a week to their lineup.`
        : `${who} in the middle of the pack, with no strong pull either way.`,
    );
  }

  if (theirs.valueDelta > 0) {
    parts.push(`They finish ${round(theirs.valueDelta)} points of value ahead.`);
  } else if (Math.abs(theirs.valueDelta) >= 1) {
    parts.push(`They take on ${round(theirs.valueDelta)} points less value than they send.`);
  }

  return parts.join(" ");
}

/**
 * The message the reader actually sends.
 *
 * Everything else on the card is written for the person looking at it. This one
 * is written for the person on the other end of it, and that changes what
 * belongs in it entirely.
 *
 * WHY IT NEVER MENTIONS WHAT THE SENDER GAINS
 *   The other manager does not care that this fixes your tight end. Telling them
 *   is worse than useless: it hands them the reason to say no. Every sentence
 *   here is about their roster, and the sender's side of the ledger, which is
 *   the whole of buildWhyYou, is deliberately absent.
 *
 * WHY IT OPENS AS A QUESTION
 *   "What do you think of" is an offer to talk. "I'll give you X for Y" is a
 *   demand with a number attached, and it invites a yes or a no rather than a
 *   conversation. The difference costs nothing and is most of whether a real
 *   person replies.
 *
 * Nothing here oversells. No adjectives about the players, no claim the deal is
 * good, no ask for a decision. It states what is being proposed and what it
 * would do for them, and stops.
 */
export function buildPitch(params: {
  /** What the reader sends, which the other manager receives. */
  outgoing: SuggestionAsset[];
  /** What the reader receives, which the other manager sends. */
  incoming: SuggestionAsset[];
  /** The other manager's side of the ledger. */
  theirs: SideImpact;
  direction: TeamDirection;
  /** Gap between the two sides, 0 to 1. Decides whether "even" is a fair word. */
  valueGap: number;
}): string {
  const opener = `What do you think of me sending you ${listAssets(params.outgoing)}, and you sending back ${listAssets(params.incoming)}?`;

  const reasons: string[] = [];
  const { theirs, direction } = params;

  if (direction === "rebuild") {
    if (theirs.pickCountDelta > 0) {
      reasons.push(
        `It gets you ${theirs.pickCountDelta} more draft ${theirs.pickCountDelta === 1 ? "pick" : "picks"} for a season you are not chasing.`,
      );
    }
    if (
      theirs.ageDelta !== null &&
      theirs.ageDelta < -RANK_THRESHOLDS.MEANINGFULLY_YOUNGER
    ) {
      reasons.push(
        `It takes about ${Math.abs(theirs.ageDelta).toFixed(1)} years off your average age.`,
      );
    }
  }

  if (theirs.lineupDelta !== null && theirs.lineupDelta > 0.5) {
    reasons.push(
      `It adds ${points(theirs.lineupDelta)} points a week to your starting lineup.`,
    );
  }

  // Measured as a share of the deal, not as a raw number of points. A hundred
  // points either way is a rounding error on two first-round players and a real
  // gap on two bench pieces, and the sentence has to be true in both cases.
  //
  // When they ARE behind by a visible margin, this says nothing rather than
  // apologising for it. Pointing out the shortfall in the message that proposes
  // the trade argues against the trade.
  if (params.valueGap <= RANK_THRESHOLDS.EVEN_GAP) {
    reasons.push("On value it is close to even both ways.");
  } else if (theirs.valueDelta > 0) {
    reasons.push("You come out ahead on value as well.");
  }

  // Nothing true to say about their side. Better to send the proposal on its own
  // than to invent a benefit, so the sentence that would have carried one is
  // simply absent.
  if (reasons.length === 0) return opener;

  return `${opener}\n\n${reasons.join(" ")}`;
}

/**
 * What the reader needs to know before trusting the numbers above.
 *
 * These are the differences between a figure and a good figure. A missing
 * projection does not stop a trade being suggested, but it does stop us
 * pretending the lineup arithmetic covered everyone in it.
 */
export function buildCaveats(params: {
  lineupAvailable: boolean;
  assumedPickSlots: boolean;
  missingProjection: string[];
  /** Outgoing assets minus incoming ones. Positive frees roster spots. */
  rosterSpotDelta: number;
  /**
   * Regular season games the reader has left, when a projected-wins figure was
   * reported. Null when there is no such figure to qualify.
   */
  remainingGames?: number | null;
}): string[] {
  const out: string[] = [];
  // A three-for-one is two empty roster spots on Monday morning, and in a league
  // with a full bench that is a waiver claim, not a formality.
  if (params.rosterSpotDelta >= 2) {
    out.push(
      `This leaves you ${params.rosterSpotDelta} roster spots to fill, so check you have somebody worth adding.`,
    );
  } else if (params.rosterSpotDelta <= -1) {
    const needed = Math.abs(params.rosterSpotDelta);
    out.push(
      `You take back ${needed} more ${needed === 1 ? "player" : "players"} than you send, so you may need to drop somebody.`,
    );
  }
  if (!params.lineupAvailable) {
    out.push(
      "No weekly projections are loaded for this league yet, so this deal is measured on trade value alone.",
    );
  }
  if (params.missingProjection.length > 0) {
    const names = params.missingProjection.slice(0, 3).join(", ");
    const extra = params.missingProjection.length - 3;
    out.push(
      `No weekly projection for ${names}${extra > 0 ? ` and ${extra} more` : ""}, so they count for nothing in the lineup change.`,
    );
  }
  if (params.assumedPickSlots) {
    out.push(
      "Draft slots for these picks are not set yet, so their values assume a mid-round slot.",
    );
  }
  // Late in a season the projected-wins figure is small because there is
  // barely any season left for it to land in, not because the deal is weak.
  // Without this a reader compares a week 15 number against a week 4 one and
  // concludes the engine has stopped finding good trades.
  if (
    typeof params.remainingGames === "number" &&
    params.remainingGames > 0 &&
    params.remainingGames <= LATE_SEASON_GAMES
  ) {
    out.push(
      `Only ${params.remainingGames} regular season ${params.remainingGames === 1 ? "game" : "games"} left, so a lineup change has little room to move your record.`,
    );
  }
  return out;
}

/**
 * Plural, lowercase-safe position words for the tendency sentences below.
 * Kept local rather than added to TRADE_POSITION_LABEL, which is a heading
 * word ("Running back"), not a sentence word ("running backs").
 */
const TENDENCY_POSITION_PLURAL: Record<TradePosition, string> = {
  QB: "quarterbacks",
  RB: "running backs",
  WR: "wide receivers",
  TE: "tight ends",
  K: "kickers",
  DEF: "defenses",
};

/** "trades often..." becomes "Trades often...". Straight ASCII only, so no locale surprises. */
function capitalize(s: string): string {
  if (s.length === 0) return s;
  return s[0].toUpperCase() + s.slice(1);
}

/**
 * Manager Pulse: what this counterparty's own trading history says, its own
 * short lines (`TradeSuggestion.tendencyNotes`), separate from `whyThem`.
 * Per docs/manager-pulse-plan.md section 8.4, the reader sees these as a
 * quiet line under the acceptance band, with a link to the manager's full
 * report.
 *
 * Deterministic and figure-cited throughout, per the same rule every other
 * sentence in this file already holds: nothing here is generated, and every
 * clause names the count or the rate behind it, so a below-floor tendency
 * produces no clause at all rather than a hedge. `slice` absent (no cached
 * Manager Pulse tendency, or the manager reads null for this league's game
 * type) returns an empty list, which is the ordinary "no opinion" case, not
 * an error.
 *
 * ONE SOURCE OF TRUTH FOR THE BAND-MOVING SENTENCE. `tendency.ts
 * bandAdjustment` already computes exactly when the acceptance band moves
 * (a manager with zero trades in the window, or a frequent trader who pays
 * up) and returns a `reason` fragment naming every figure behind it. This
 * used to be recomputed here as a second, independent pair of conditions
 * ("trades often" checked alone, "pays up" checked alone), which could fire
 * in combinations `bandAdjustment` never produced: a manager who trades
 * often but does NOT pay up got a "Trades often" sentence that implied the
 * band moved when it had not. Reading `bandAdjustment`'s own fragment here
 * instead makes the two impossible to disagree, by construction.
 *
 * A manager with zero trades in the window returns ONLY that one sentence:
 * every other figure a slice can offer (margin, position lean, picks moved)
 * is trivially zero or null when tradeCount is zero, so there is nothing
 * else true left to say.
 */
export function buildTendencyReasons(params: {
  slice: TendencySlice | null;
  /** The same computation that moved (or did not move) the acceptance band. */
  bandAdjustment: { steps: number; reason: string | null };
  /** Positions of the players THEY would receive in this deal (our outgoing side). */
  positionsTheyReceive: TradePosition[];
  /** Whether this deal moves a draft pick, on either side. */
  involvesPick: boolean;
  settings?: { minSample: number; frequentTradesPerSeason: number };
}): string[] {
  const slice = params.slice;
  if (!slice) return [];
  const settings = params.settings ?? {
    minSample: TENDENCY_DEFAULTS.MIN_SAMPLE,
    frequentTradesPerSeason: TENDENCY_DEFAULTS.FREQUENT_TRADES_PER_SEASON,
  };

  if (slice.tradeCount === 0) {
    return params.bandAdjustment.reason
      ? [`${capitalize(params.bandAdjustment.reason)}.`]
      : ["Has not completed a trade. 0 trades in the window."];
  }

  const out: string[] = [];

  if (params.bandAdjustment.steps > 0 && params.bandAdjustment.reason) {
    out.push(`${capitalize(params.bandAdjustment.reason)}.`);
  }

  if (slice.tradeCount >= settings.minSample) {
    const boughtPosition = params.positionsTheyReceive.find((position) => {
      const flow = slice.positionAppetite[position];
      return typeof flow === "number" && flow > 0;
    });
    if (boughtPosition) {
      out.push(
        `Buys ${TENDENCY_POSITION_PLURAL[boughtPosition]}. Net value in at the position, over ${slice.tradeCount} trades.`,
      );
    }
  }

  if (params.involvesPick && slice.picksTraded === 0 && slice.tradeCount >= settings.minSample) {
    out.push(`Never trades picks. 0 moved in ${slice.tradeCount} trades.`);
  }

  return out;
}
