/**
 * The sentences.
 *
 * Every number this feature produces is already on the card. These lines exist
 * because a column of deltas does not tell a manager whether to send the offer,
 * and because the person this site is built for is listening to the page rather
 * than scanning it. A screen reader user should be able to hear the headline,
 * hear one sentence about their own side, hear one about the other team, and
 * know enough to decide.
 *
 * Nothing here is generated by a model and nothing here is invented. Each
 * sentence is assembled from figures the engine computed, and when a figure is
 * missing the sentence that would have used it is dropped rather than softened
 * into something vague. A caveat list carries what would otherwise make a number
 * misleading.
 */

import { RANK_THRESHOLDS } from "./rank";
import type {
  SideImpact,
  SuggestionAsset,
  TeamDirection,
  TradeGoal,
} from "./types";

/** "Bijan Robinson", "Bijan Robinson and a 2027 1st", "A, B, and C". */
export function listAssets(assets: SuggestionAsset[]): string {
  const names = assets.map((a) => (a.kind === "player" ? a.name : a.label));
  if (names.length === 0) return "nothing";
  if (names.length === 1) return names[0];
  if (names.length === 2) return `${names[0]} and ${names[1]}`;
  return `${names.slice(0, -1).join(", ")}, and ${names[names.length - 1]}`;
}

/** Points per week, signed, to one decimal. */
function points(delta: number): string {
  const rounded = Math.abs(delta).toFixed(1);
  return `${delta >= 0 ? "+" : "-"}${rounded}`;
}

function round(value: number): string {
  return Math.round(Math.abs(value)).toLocaleString("en-US");
}

export function buildHeadline(
  incoming: SuggestionAsset[],
  outgoing: SuggestionAsset[],
  teamName: string,
): string {
  return `Send ${listAssets(outgoing)} to ${teamName} for ${listAssets(incoming)}.`;
}

/**
 * The reader's side.
 *
 * Lineup change leads whenever we have one, because it is the part that happens
 * on Sunday. Value follows, and it is phrased as a gap rather than a verdict:
 * "you give up a little value" is the truth, and calling the same trade a loss
 * would misread a deal that turns a bench player into a starter.
 */
export function buildWhyYou(
  mine: SideImpact,
  goal: TradeGoal,
  positionHelped: string | null,
): string {
  const parts: string[] = [];

  if (mine.lineupDelta !== null && Math.abs(mine.lineupDelta) >= 0.1) {
    const where = positionHelped ? ` at ${positionHelped}` : "";
    parts.push(
      mine.lineupDelta > 0
        ? `Your starting lineup gains ${points(mine.lineupDelta)} points a week${where}.`
        : `Your starting lineup gives up ${points(mine.lineupDelta)} points a week${where}.`,
    );
  }

  if (Math.abs(mine.valueDelta) >= 1) {
    parts.push(
      mine.valueDelta > 0
        ? `You come out ${round(mine.valueDelta)} points of trade value ahead.`
        : `You give up ${round(mine.valueDelta)} points of trade value to do it.`,
    );
  } else {
    parts.push("The two sides are level on trade value.");
  }

  if (goal === "get-younger" && mine.ageDelta !== null && mine.ageDelta < 0) {
    parts.push(`Your roster gets ${Math.abs(mine.ageDelta).toFixed(1)} years younger on average.`);
  }
  if (goal === "add-picks" && mine.pickCountDelta > 0) {
    parts.push(
      `You add ${mine.pickCountDelta} draft ${mine.pickCountDelta === 1 ? "pick" : "picks"}.`,
    );
  }

  return parts.join(" ");
}

/**
 * The other manager's side.
 *
 * Written from their situation rather than ours, because that is the argument
 * the reader has to make in the league chat. If the honest answer is that the
 * deal only works for us, the sentence says so instead of dressing it up.
 */
export function buildWhyThem(
  theirs: SideImpact,
  direction: TeamDirection,
  teamName: string,
  statusLabel: string | null,
): string {
  const who = statusLabel ? `${teamName} reads as a ${statusLabel.toLowerCase()}` : teamName;
  const parts: string[] = [];

  // The same bar the acceptance band uses. Arguing "it makes them younger" off a
  // tenth of a year would be an argument the rest of the engine does not credit,
  // and a reader who repeats it in their league chat gets asked how much younger.
  const meaningfullyYounger =
    theirs.ageDelta !== null && theirs.ageDelta < -RANK_THRESHOLDS.MEANINGFULLY_YOUNGER;

  if (direction === "rebuild") {
    if (theirs.pickCountDelta > 0) {
      parts.push(
        `${who}, and this hands them ${theirs.pickCountDelta} more draft ${theirs.pickCountDelta === 1 ? "pick" : "picks"} for a season they are not winning.`,
      );
    } else if (meaningfullyYounger) {
      parts.push(
        `${who}, and this takes ${Math.abs(theirs.ageDelta as number).toFixed(1)} years off their average age.`,
      );
    } else {
      parts.push(`${who}, so the case has to be the value.`);
    }
  } else if (direction === "win-now") {
    if (theirs.lineupDelta !== null && theirs.lineupDelta > 0) {
      parts.push(
        `${who} chasing this season, and this adds ${points(theirs.lineupDelta)} points a week to their starting lineup.`,
      );
    } else {
      parts.push(`${who} chasing this season, so the case has to be the value.`);
    }
  } else {
    parts.push(
      theirs.lineupDelta !== null && theirs.lineupDelta > 0
        ? `${who} in the middle of the pack, and this adds ${points(theirs.lineupDelta)} points a week to their lineup.`
        : `${who} in the middle of the pack, with no strong pull either way.`,
    );
  }

  if (theirs.valueDelta > 0) {
    parts.push(`They finish ${round(theirs.valueDelta)} points of value ahead.`);
  } else if (Math.abs(theirs.valueDelta) >= 1) {
    parts.push(`They take on ${round(theirs.valueDelta)} points less value than they send.`);
  }

  return parts.join(" ");
}

/**
 * The message the reader actually sends.
 *
 * Everything else on the card is written for the person looking at it. This one
 * is written for the person on the other end of it, and that changes what
 * belongs in it entirely.
 *
 * WHY IT NEVER MENTIONS WHAT THE SENDER GAINS
 *   The other manager does not care that this fixes your tight end. Telling them
 *   is worse than useless: it hands them the reason to say no. Every sentence
 *   here is about their roster, and the sender's side of the ledger, which is
 *   the whole of buildWhyYou, is deliberately absent.
 *
 * WHY IT OPENS AS A QUESTION
 *   "What do you think of" is an offer to talk. "I'll give you X for Y" is a
 *   demand with a number attached, and it invites a yes or a no rather than a
 *   conversation. The difference costs nothing and is most of whether a real
 *   person replies.
 *
 * Nothing here oversells. No adjectives about the players, no claim the deal is
 * good, no ask for a decision. It states what is being proposed and what it
 * would do for them, and stops.
 */
export function buildPitch(params: {
  /** What the reader sends, which the other manager receives. */
  outgoing: SuggestionAsset[];
  /** What the reader receives, which the other manager sends. */
  incoming: SuggestionAsset[];
  /** The other manager's side of the ledger. */
  theirs: SideImpact;
  direction: TeamDirection;
  /** Gap between the two sides, 0 to 1. Decides whether "even" is a fair word. */
  valueGap: number;
}): string {
  const opener = `What do you think of me sending you ${listAssets(params.outgoing)}, and you sending back ${listAssets(params.incoming)}?`;

  const reasons: string[] = [];
  const { theirs, direction } = params;

  if (direction === "rebuild") {
    if (theirs.pickCountDelta > 0) {
      reasons.push(
        `It gets you ${theirs.pickCountDelta} more draft ${theirs.pickCountDelta === 1 ? "pick" : "picks"} for a season you are not chasing.`,
      );
    }
    if (
      theirs.ageDelta !== null &&
      theirs.ageDelta < -RANK_THRESHOLDS.MEANINGFULLY_YOUNGER
    ) {
      reasons.push(
        `It takes about ${Math.abs(theirs.ageDelta).toFixed(1)} years off your average age.`,
      );
    }
  }

  if (theirs.lineupDelta !== null && theirs.lineupDelta > 0.5) {
    reasons.push(
      `It adds ${points(theirs.lineupDelta)} points a week to your starting lineup.`,
    );
  }

  // Measured as a share of the deal, not as a raw number of points. A hundred
  // points either way is a rounding error on two first-round players and a real
  // gap on two bench pieces, and the sentence has to be true in both cases.
  //
  // When they ARE behind by a visible margin, this says nothing rather than
  // apologising for it. Pointing out the shortfall in the message that proposes
  // the trade argues against the trade.
  if (params.valueGap <= RANK_THRESHOLDS.EVEN_GAP) {
    reasons.push("On value it is close to even both ways.");
  } else if (theirs.valueDelta > 0) {
    reasons.push("You come out ahead on value as well.");
  }

  // Nothing true to say about their side. Better to send the proposal on its own
  // than to invent a benefit, so the sentence that would have carried one is
  // simply absent.
  if (reasons.length === 0) return opener;

  return `${opener}\n\n${reasons.join(" ")}`;
}

/**
 * What the reader needs to know before trusting the numbers above.
 *
 * These are the differences between a figure and a good figure. A missing
 * projection does not stop a trade being suggested, but it does stop us
 * pretending the lineup arithmetic covered everyone in it.
 */
export function buildCaveats(params: {
  lineupAvailable: boolean;
  assumedPickSlots: boolean;
  missingProjection: string[];
  /** Outgoing assets minus incoming ones. Positive frees roster spots. */
  rosterSpotDelta: number;
}): string[] {
  const out: string[] = [];
  // A three-for-one is two empty roster spots on Monday morning, and in a league
  // with a full bench that is a waiver claim, not a formality.
  if (params.rosterSpotDelta >= 2) {
    out.push(
      `This leaves you ${params.rosterSpotDelta} roster spots to fill, so check you have somebody worth adding.`,
    );
  } else if (params.rosterSpotDelta <= -1) {
    const needed = Math.abs(params.rosterSpotDelta);
    out.push(
      `You take back ${needed} more ${needed === 1 ? "player" : "players"} than you send, so you may need to drop somebody.`,
    );
  }
  if (!params.lineupAvailable) {
    out.push(
      "No weekly projections are loaded for this league yet, so this deal is measured on trade value alone.",
    );
  }
  if (params.missingProjection.length > 0) {
    const names = params.missingProjection.slice(0, 3).join(", ");
    const extra = params.missingProjection.length - 3;
    out.push(
      `No weekly projection for ${names}${extra > 0 ? ` and ${extra} more` : ""}, so they count for nothing in the lineup change.`,
    );
  }
  if (params.assumedPickSlots) {
    out.push(
      "Draft slots for these picks are not set yet, so their values assume a mid-round slot.",
    );
  }
  return out;
}
